In [1]:
# # Create a directory for the files
# !mkdir /kaggle/working/pymorphy3

# # Download pdfplumber and all its dependencies
# !pip download pymorphy3 -d /kaggle/working/pymorphy3
# !pip download pymorphy3-dicts-uk -d /kaggle/working/pymorphy3
# !pip download rank-bm25 -d /kaggle/working/pymorphy3

# import shutil
# from IPython.display import FileLink
# # 1. Zip the folder (Change 'my_folder' to your folder's name)
# shutil.make_archive('pymorphy3', 'zip', '/kaggle/working/pymorphy3')

# # 2. Generate the clickable link
# FileLink(r'pymorphy3.zip')

In [2]:
# # Create a directory for the files
# !mkdir /kaggle/working/pymupdf4llm_pkg

# # Download pymupdf4llm with layout extras and all dependencies
# !pip download "pymupdf4llm[layout]==0.3.4" -d /kaggle/working/pymupdf4llm_pkg

# # (Optional but safer) Explicitly ensure key dependencies are included
# !pip download pymupdf -d /kaggle/working/pymupdf4llm_pkg
# !pip download pillow -d /kaggle/working/pymupdf4llm_pkg

# import shutil
# from IPython.display import FileLink

# # Zip the folder
# shutil.make_archive('pymupdf4llm_pkg', 'zip', '/kaggle/working/pymupdf4llm_pkg')

# # Generate download link
# FileLink(r'pymupdf4llm_pkg.zip')

In [3]:
!ls -la /kaggle/input/packages-unlp26/

total 4
drwxr-xr-x 9 nobody nogroup    0 Mar 21 14:49 .
drwxr-xr-x 6 root   root    4096 Mar 30 10:16 ..
drwxr-xr-x 3 nobody nogroup    0 Mar 21 14:49 llamacpp_wheels
drwxr-xr-x 3 nobody nogroup    0 Mar 21 14:49 pdfplumber_wheels
drwxr-xr-x 2 nobody nogroup    0 Mar 21 14:49 pymorphy3
drwxr-xr-x 3 nobody nogroup    0 Mar 21 14:49 pymupdf
drwxr-xr-x 2 nobody nogroup    0 Mar 21 14:49 pymupdf4llm
drwxr-xr-x 3 nobody nogroup    0 Mar 21 14:49 tantivy
drwxr-xr-x 3 nobody nogroup    0 Mar 21 14:49 uk_spacy_wheels

In [4]:
!pip install --no-index --find-links=/kaggle/input/packages-unlp26/llamacpp_wheels/kaggle/working/llamacpp_wheels llama-cpp-python

Looking in links: /kaggle/input/packages-unlp26/llamacpp_wheels/kaggle/working/llamacpp_wheels
Processing /kaggle/input/packages-unlp26/llamacpp_wheels/kaggle/working/llamacpp_wheels/llama_cpp_python-0.3.16-cp312-cp312-linux_x86_64.whl
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from llama-cpp-python) (4.15.0)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from llama-cpp-python) (2.0.2)
Processing /kaggle/input/packages-unlp26/llamacpp_wheels/kaggle/working/llamacpp_wheels/diskcache-5.6.3-py3-none-any.whl (from llama-cpp-python)
Requirement already satisfied: jinja2>=2.11.3 in /usr/local/lib/python3.12/dist-packages (from llama-cpp-python) (3.1.6)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.11.3->llama-cpp-python) (3.0.3)
Installing collected packages: diskcache, llama-cpp-python
Successfully installed diskcache-5.6.3 llama-cpp-python-0.3.16

In [5]:
# !pip install --no-index --find-links=/kaggle/input/datasets/trokhymovych/packages-unlp26/pdfplumber_wheels/kaggle/working/pdfplumber_wheels pdfplumber
# !pip install --no-index --find-links=/kaggle/input/datasets/trokhymovych/packages-unlp26/pymupdf/kaggle/working/pymupdf pymupdf
# !pip install --no-index --find-links=/kaggle/input/datasets/trokhymovych/packages-unlp26/tantivy/tantivy tantivy
# !pip install --no-index --find-links=/kaggle/input/datasets/trokhymovych/packages-unlp26/pymupdf4llm pymupdf4llm[ocr,layout]
# !pip install --no-index --find-links=/kaggle/input/packages-unlp26/pymupdf4llm pymupdf4llm[ocr,layout]
!pip install --no-index --find-links=/kaggle/input/datasets/trokhymovych/yobanii-parser pymupdf4llm[layout]=='0.3.4'
!pip install --no-index --find-links=/kaggle/input/packages-unlp26/pymorphy3 pymorphy3
!pip install --no-index --find-links=/kaggle/input/packages-unlp26/pymorphy3 pymorphy3-dicts-uk
!pip install --no-index --find-links=/kaggle/input/packages-unlp26/pymorphy3 rank-bm25

Looking in links: /kaggle/input/datasets/trokhymovych/yobanii-parser
Processing /kaggle/input/datasets/trokhymovych/yobanii-parser/pymupdf4llm-0.3.4-py3-none-any.whl (from pymupdf4llm[layout]==0.3.4)
Processing /kaggle/input/datasets/trokhymovych/yobanii-parser/pymupdf-1.27.2.2-cp310-abi3-manylinux_2_28_x86_64.whl (from pymupdf4llm==0.3.4->pymupdf4llm[layout]==0.3.4)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from pymupdf4llm==0.3.4->pymupdf4llm[layout]==0.3.4) (0.9.0)
Processing /kaggle/input/datasets/trokhymovych/yobanii-parser/pymupdf_layout-1.27.2.2-cp310-abi3-manylinux_2_28_x86_64.whl (from pymupdf4llm[layout]==0.3.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from pymupdf-layout>=1.27.1->pymupdf4llm[layout]==0.3.4) (6.0.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pymupdf-layout>=1.27.1->pymupdf4llm[layout]==0.3.4) (2.0.2)
Processing /kaggle/input/datasets/trokhymovych/yobanii-parser/onnxruntime-1.24.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (from pymupdf-layout>=1.27.1->pymupdf4llm[layout]==0.3.4)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from pymupdf-layout>=1.27.1->pymupdf4llm[layout]==0.3.4) (3.6.1)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime->pymupdf-layout>=1.27.1->pymupdf4llm[layout]==0.3.4) (25.12.19)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from onnxruntime->pymupdf-layout>=1.27.1->pymupdf4llm[layout]==0.3.4) (25.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime->pymupdf-layout>=1.27.1->pymupdf4llm[layout]==0.3.4) (5.29.5)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime->pymupdf-layout>=1.27.1->pymupdf4llm[layout]==0.3.4) (1.14.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->onnxruntime->pymupdf-layout>=1.27.1->pymupdf4llm[layout]==0.3.4) (1.3.0)
Installing collected packages: pymupdf, pymupdf4llm, onnxruntime, pymupdf-layout
Successfully installed onnxruntime-1.24.4 pymupdf-1.27.2.2 pymupdf-layout-1.27.2.2 pymupdf4llm-0.3.4
Looking in links: /kaggle/input/packages-unlp26/pymorphy3
Processing /kaggle/input/packages-unlp26/pymorphy3/pymorphy3-2.0.6-py3-none-any.whl
Processing /kaggle/input/packages-unlp26/pymorphy3/dawg2_python-0.9.0-py3-none-any.whl (from pymorphy3)
Processing /kaggle/input/packages-unlp26/pymorphy3/pymorphy3_dicts_ru-2.4.417150.4580142-py2.py3-none-any.whl (from pymorphy3)
Requirement already satisfied: setuptools>=68.2.2 in /usr/local/lib/python3.12/dist-packages (from pymorphy3) (75.2.0)
Installing collected packages: pymorphy3-dicts-ru, dawg2-python, pymorphy3
Successfully installed dawg2-python-0.9.0 pymorphy3-2.0.6 pymorphy3-dicts-ru-2.4.417150.4580142
Looking in links: /kaggle/input/packages-unlp26/pymorphy3
Processing /kaggle/input/packages-unlp26/pymorphy3/pymorphy3_dicts_uk-2.4.1.1.1663094765-py2.py3-none-any.whl
Installing collected packages: pymorphy3-dicts-uk
Successfully installed pymorphy3-dicts-uk-2.4.1.1.1663094765
Looking in links: /kaggle/input/packages-unlp26/pymorphy3
Processing /kaggle/input/packages-unlp26/pymorphy3/rank_bm25-0.2.2-py3-none-any.whl
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rank-bm25) (2.0.2)
Installing collected packages: rank-bm25
Successfully installed rank-bm25-0.2.2

In [6]:
import sys

sys.path.append("..")
TRAIN = False

# optimization of weights of different searches
OPTIMIZE = False
MAX_COMBOS = 500

if TRAIN:
    DATA_PATH = "/kaggle/input/competitions/unlp-2026-shared-task-on-multi-domain-document-understanding/train/*/*.pdf"
    DOMAIN_PATH = (
        "/kaggle/input/competitions/unlp-2026-shared-task-on-multi-domain-document-understanding/train/*/readme.txt"
    )
    TRAIN_PATH = "/kaggle/input/datasets/nazariinyzhnyk/unlp-large-chunk/data/dev_questions.csv"
    N_PAGES_COLUMN = "N_Pages"
else:
    DATA_PATH = "/kaggle/input/competitions/unlp-2026-shared-task-on-multi-domain-document-understanding/test/*/*.pdf"
    DOMAIN_PATH = (
        "/kaggle/input/competitions/unlp-2026-shared-task-on-multi-domain-document-understanding/test/*/readme.txt"
    )
    TRAIN_PATH = "/kaggle/input/competitions/unlp-2026-shared-task-on-multi-domain-document-understanding/test.csv"
    N_PAGES_COLUMN = "n_pages"


IMAGES_PATH = "/kaggle/working/images/"
EMBEDDING_MODEL = "/kaggle/input/models/trokhymovych/perplexity-06/transformers/default/1/pplx_model_06"
EMBEDDING_MODEL_BATCH_SIZE = 4
MAX_PAGE_SIZE = 5000

In [7]:
from dataclasses import dataclass

# Getting all files:
import glob
import os
import sys

import numpy as np
import pandas as pd
from tqdm import tqdm

try:
    _HAS_FITZ = True
except Exception:
    _HAS_FITZ = False


from rank_bm25 import BM25Okapi

In [8]:
pd.set_option("display.max_rows", 500)
pd.set_option("display.max_columns", 500)
pd.set_option("display.width", 1000)

In [9]:
from llama_cpp import Llama
import torch
from transformers import logging

In [10]:
import warnings

warnings.simplefilter("ignore")
# Suppress INFO/USER warnings
logging.set_verbosity_error()

In [11]:
os.path.exists(TRAIN_PATH)

True

# Modules:

In [12]:
import re

import pymorphy3

# Initialize once outside the function for performance
morph = pymorphy3.MorphAnalyzer(lang="uk")
UK_STOP_WORDS = [
    "а",
    "аби",
    "абиде",
    "абиким",
    "абикого",
    "абиколи",
    "абикому",
    "абикуди",
    "абихто",
    "абичий",
    "абичийого",
    "абичийому",
    "абичим",
    "абичию",
    "абичия",
    "абичиє",
    "абичиєму",
    "абичиєю",
    "абичиєї",
    "абичиї",
    "абичиїй",
    "абичиїм",
    "абичиїми",
    "абичиїх",
    "абичого",
    "абичому",
    "абищо",
    "абияка",
    "абияке",
    "абиякий",
    "абияким",
    "абиякими",
    "абияких",
    "абиякого",
    "абиякому",
    "абиякою",
    "абиякої",
    "абияку",
    "абиякі",
    "абиякій",
    "абиякім",
    "або",
    "абощо",
    "авжеж",
    "авось",
    "ага",
    "ад",
    "адже",
    "аж",
    "ажень",
    "аз",
    "ай",
    "але",
    "ало",
    "амінь",
    "ант",
    "ану",
    "ані",
    "аніде",
    "аніж",
    "анізащо",
    "аніким",
    "анікого",
    "анікогісінько",
    "аніколи",
    "анікому",
    "аніскільки",
    "аніхто",
    "анічим",
    "анічого",
    "анічогісінько",
    "анічому",
    "аніщо",
    "аніяка",
    "аніяке",
    "аніякий",
    "аніяким",
    "аніякими",
    "аніяких",
    "аніякого",
    "аніякому",
    "аніякою",
    "аніякої",
    "аніяку",
    "аніякі",
    "аніякій",
    "аніякім",
    "аніякісенька",
    "аніякісеньке",
    "аніякісенький",
    "аніякісеньким",
    "аніякісенькими",
    "аніякісеньких",
    "аніякісенького",
    "аніякісенькому",
    "аніякісенькою",
    "аніякісенької",
    "аніякісеньку",
    "аніякісенькі",
    "аніякісенькій",
    "аніякісенькім",
    "аніякісінька",
    "аніякісіньке",
    "аніякісінький",
    "аніякісіньким",
    "аніякісінькими",
    "аніякісіньких",
    "аніякісінького",
    "аніякісінькому",
    "аніякісінькою",
    "аніякісінької",
    "аніякісіньку",
    "аніякісінькі",
    "аніякісінькій",
    "аніякісінькім",
    "ат",
    "ато",
    "атож",
    "ау",
    "ах",
    "ач",
    "ачей",
    "аякже",
    "б",
    "ба",
    "багато",
    "багатьма",
    "багатьом",
    "багатьох",
    "баз",
    "бай",
    "бат",
    "бах",
    "бац",
    "баш",
    "бе",
    "беж",
    "без",
    "безперервно",
    "бел",
    "бер",
    "би",
    "бир",
    "бич",
    "близько",
    "близько від",
    "бо",
    "бов",
    "бод",
    "бодай",
    "боз",
    "бош",
    "був",
    "буває",
    "буде",
    "будем",
    "будемо",
    "будете",
    "будеш",
    "буду",
    "будуть",
    "будь",
    "будь ласка",
    "будьмо",
    "будьте",
    "була",
    "були",
    "було",
    "бути",
    "бух",
    "буц",
    "буцім",
    "буцімто",
    "бі",
    "біб",
    "більш",
    "більше",
    "біля",
    "в",
    "в бік",
    "в залежності від",
    "в міру",
    "в напрямі до",
    "в порівнянні з",
    "в процесі",
    "в результаті",
    "в ролі",
    "в силу",
    "в сторону",
    "в супроводі",
    "в ході",
    "в ім'я",
    "в інтересах",
    "вад",
    "важлива",
    "важливе",
    "важливий",
    "важливі",
    "вак",
    "вам",
    "вами",
    "ван",
    "вас",
    "ват",
    "ваш",
    "ваша",
    "ваше",
    "вашим",
    "вашими",
    "ваших",
    "вашого",
    "вашому",
    "вашою",
    "вашої",
    "вашу",
    "ваші",
    "вашій",
    "вашім",
    "ввесь",
    "вві",
    "вгору",
    "вдалині",
    "вед",
    "верх",
    "весь",
    "вех",
    "вже",
    "вздовж",
    "ви",
    "виз",
    "вис",
    "височині",
    "вище ",
    "вйо",
    "власне",
    "властиво",
    "вміти",
    "внаслідок",
    "вниз",
    "внизу",
    "во",
    "вон",
    "вона",
    "вони",
    "воно",
    "восьмий",
    "вперед",
    "вподовж",
    "впоперек",
    "впритиск",
    "впритул",
    "впродовж",
    "впрост",
    "все",
    "всередині",
    "всею",
    "вслід",
    "всупереч",
    "всього",
    "всьому",
    "всю",
    "всюди",
    "вся",
    "всяк",
    "всяка",
    "всяке",
    "всякий",
    "всяким",
    "всякими",
    "всяких",
    "всякого",
    "всякому",
    "всякою",
    "всякої",
    "всяку",
    "всякі",
    "всякій",
    "всякім",
    "всі",
    "всій",
    "всіляка",
    "всіляке",
    "всілякий",
    "всіляким",
    "всілякими",
    "всіляких",
    "всілякого",
    "всілякому",
    "всілякою",
    "всілякої",
    "всіляку",
    "всілякі",
    "всілякій",
    "всілякім",
    "всім",
    "всіма",
    "всіх",
    "всією",
    "всієї",
    "втім",
    "ві",
    "віг",
    "від",
    "від імені",
    "віддалік від",
    "відколи",
    "відносно",
    "відповідно",
    "відповідно до",
    "відсотків",
    "відтепер",
    "відтоді",
    "він",
    "вісім",
    "вісімнадцятий",
    "вісімнадцять",
    "віт",
    "віф",
    "віх",
    "віц",
    "віщо",
    "віщось",
    "г",
    "га",
    "гав",
    "гаразд",
    "ге",
    "гез",
    "гем",
    "геп",
    "гет",
    "геть",
    "гех",
    "ги",
    "гик",
    "гир",
    "гич",
    "гм",
    "го",
    "говорив",
    "гог",
    "гоп",
    "гоц",
    "гу",
    "гуп",
    "д",
    "да",
    "давай",
    "давати",
    "давно",
    "далеко",
    "далеко від",
    "далі",
    "даром",
    "два",
    "двадцятий",
    "двадцять",
    "дванадцятий",
    "дванадцять",
    "двох",
    "дві",
    "де",
    "дев'ятий",
    "дев'ятнадцятий",
    "дев'ятнадцять",
    "дев'ять",
    "дедалі",
    "деким",
    "декого",
    "деколи",
    "декому",
    "декотра",
    "декотре",
    "декотрий",
    "декотрим",
    "декотрими",
    "декотрих",
    "декотрого",
    "декотрому",
    "декотрою",
    "декотрої",
    "декотру",
    "декотрі",
    "декотрій",
    "декотрім",
    "декілька",
    "декільком",
    "декількома",
    "декількох",
    "декім",
    "десь",
    "десятий",
    "десять",
    "дехто",
    "дечий",
    "дечийого",
    "дечийому",
    "дечим",
    "дечию",
    "дечия",
    "дечиє",
    "дечиєму",
    "дечиєю",
    "дечиєї",
    "дечиї",
    "дечиїй",
    "дечиїм",
    "дечиїми",
    "дечиїх",
    "дечого",
    "дечому",
    "дечім",
    "дещо",
    "деяка",
    "деяке",
    "деякий",
    "деяким",
    "деякими",
    "деяких",
    "деякого",
    "деякому",
    "деякою",
    "деякої",
    "деяку",
    "деякі",
    "деякій",
    "деякім",
    "деінде",
    "для",
    "до",
    "добре",
    "довго",
    "довкола",
    "довкіл",
    "дог",
    "доки",
    "допоки",
    "допіру",
    "досить",
    "досі",
    "дотепер",
    "доти",
    "другий",
    "друго",
    "дуже",
    "дякую",
    "дійсно",
    "діл",
    "е",
    "еге",
    "еж",
    "ей",
    "ерг",
    "ест",
    "ет",
    "ех",
    "еч",
    "ж",
    "же",
    "жоден",
    "жодна",
    "жодне",
    "жодний",
    "жодним",
    "жодними",
    "жодних",
    "жодного",
    "жодному",
    "жодною",
    "жодної",
    "жодну",
    "жодні",
    "жодній",
    "жоднім",
    "жоднісінька",
    "жоднісіньке",
    "жоднісінький",
    "жоднісіньким",
    "жоднісінькими",
    "жоднісіньких",
    "жоднісінького",
    "жоднісінькому",
    "жоднісінькою",
    "жоднісінької",
    "жоднісіньку",
    "жоднісінькі",
    "жоднісінькій",
    "жоднісінькім",
    "жуз",
    "з",
    "з метою",
    "з нагоди",
    "з приводу",
    "з розрахунку на",
    "з-за",
    "з-над",
    "з-перед",
    "з-поза",
    "з-поміж",
    "з-понад",
    "з-поперед",
    "з-посеред",
    "з-проміж",
    "з-під",
    "з-серед",
    "за",
    "за винятком",
    "за допомогою",
    "за посередництвом",
    "за рахунок",
    "завгодно",
    "завдяки",
    "завжди",
    "завше",
    "задля",
    "зазвичай",
    "зайнята",
    "зайнятий",
    "зайнято",
    "зайняті",
    "залежно",
    "залежно від",
    "замість",
    "занадто",
    "заради",
    "зараз",
    "зас",
    "зате",
    "збоку",
    "збоку від",
    "зважаючи на",
    "зверх ",
    "зверху",
    "звичайно",
    "звиш",
    "звідки",
    "звідкилясь",
    "звідкись",
    "звідкіль",
    "звідкіля",
    "звідкілясь",
    "звідси",
    "звідсіль",
    "звідсіля",
    "звідти",
    "звідтіль",
    "звідтіля",
    "звідусюди",
    "звідусіль",
    "звідціля",
    "згідно з",
    "здається",
    "здовж",
    "зем",
    "зет",
    "ззаду",
    "зиз",
    "зик",
    "значить",
    "знову",
    "зо",
    "зовсім",
    "зсередини",
    "зух",
    "зі",
    "зіс",
    "и",
    "ич",
    "й",
    "ймовірно",
    "йно",
    "йо",
    "його",
    "йой",
    "йол",
    "йому",
    "йор",
    "йот",
    "йох",
    "к",
    "каже",
    "каз",
    "кар",
    "каф",
    "ках",
    "ке",
    "кед",
    "кет",
    "кеш",
    "кив",
    "кий",
    "кил",
    "ким",
    "кимось",
    "кимсь",
    "ких",
    "киш",
    "коб",
    "коби",
    "кого",
    "когось",
    "кожен",
    "кожна",
    "кожне",
    "кожний",
    "кожним",
    "кожними",
    "кожних",
    "кожного",
    "кожному",
    "кожною",
    "кожної",
    "кожну",
    "кожні",
    "кожній",
    "кожнім",
    "кожнісінька",
    "кожнісіньке",
    "кожнісінький",
    "кожнісіньким",
    "кожнісінькими",
    "кожнісіньких",
    "кожнісінького",
    "кожнісінькому",
    "кожнісінькою",
    "кожнісінької",
    "кожнісіньку",
    "кожнісінькі",
    "кожнісінькій",
    "кожнісінькім",
    "коли",
    "колись",
    "коло",
    "кому",
    "комусь",
    "котра",
    "котрась",
    "котре",
    "котресь",
    "котрий",
    "котрийсь",
    "котрим",
    "котрими",
    "котримись",
    "котримось",
    "котримсь",
    "котрих",
    "котрихось",
    "котрихсь",
    "котрого",
    "котрогось",
    "котрому",
    "котромусь",
    "котрою",
    "котроюсь",
    "котрої",
    "котроїсь",
    "котру",
    "котрусь",
    "котрі",
    "котрій",
    "котрійсь",
    "котрім",
    "котрімсь",
    "котрісь",
    "коц",
    "коч",
    "коштом",
    "край",
    "краще",
    "кру",
    "круг",
    "кругом",
    "крю",
    "кря",
    "крізь",
    "крім",
    "куди",
    "кудись",
    "кудою",
    "кілька",
    "кільком",
    "кількома",
    "кількох",
    "кім",
    "кімось",
    "кімсь",
    "кінець",
    "л",
    "лаж",
    "лап",
    "лас",
    "лат",
    "ле",
    "ледве",
    "ледь",
    "лет",
    "лиш",
    "лише",
    "лишень",
    "лум",
    "луп",
    "лут",
    "льє",
    "люди",
    "людина",
    "ля",
    "лі",
    "ліворуч від",
    "лік",
    "лім",
    "м",
    "мабуть",
    "майже",
    "мало",
    "мати",
    "мац",
    "ме",
    "меж",
    "мене",
    "менше",
    "мені",
    "мерсі",
    "мет",
    "мжа",
    "ми",
    "мимо ",
    "миру",
    "мит",
    "мною",
    "мо",
    "мов",
    "мовби",
    "мовбито",
    "могла",
    "могли",
    "могло",
    "мого",
    "могти",
    "мож",
    "може",
    "можем",
    "можемо",
    "можете",
    "можеш",
    "можна",
    "можу",
    "можуть",
    "можіть",
    "мой",
    "мол",
    "мою",
    "моя",
    "моє",
    "моєму",
    "моєю",
    "моєї",
    "мої",
    "моїй",
    "моїм",
    "моїми",
    "моїх",
    "му",
    "мі",
    "міг",
    "між",
    "мій",
    "мільйонів",
    "н",
    "на",
    "на адресу",
    "на базі",
    "на благо",
    "на випадок",
    "на відміну від",
    "на засадах",
    "на знак",
    "на зразок",
    "на користь",
    "на кшталт",
    "на межі",
    "на основі",
    "на противагу",
    "на підставі",
    "на честь",
    "на чолі",
    "на ґрунті",
    "навколо",
    "навкруг",
    "навкруги ",
    "навкіл",
    "навпаки",
    "навперейми",
    "навпроти",
    "навіть",
    "навіщо",
    "навіщось",
    "нагорі",
    "над",
    "надо",
    "надовкола",
    "надокола",
    "наді",
    "назавжди",
    "назад",
    "назустріч",
    "най",
    "найбільш",
    "нам",
    "нами",
    "наоколо ",
    "наокруг ",
    "наокруги ",
    "наокіл",
    "наперед",
    "напередодні",
    "напереді",
    "наперекір",
    "напереріз",
    "наприкінці",
    "напроти",
    "нарешті",
    "нарівні з",
    "нас",
    "насеред",
    "насподі",
    "наспід",
    "настрічу",
    "насупроти",
    "насупротив ",
    "нате",
    "наче",
    "начеб",
    "начебто",
    "наш",
    "наша",
    "наше",
    "нашим",
    "нашими",
    "наших",
    "нашого",
    "нашому",
    "нашою",
    "нашої",
    "нашу",
    "наші",
    "нашій",
    "нашім",
    "не",
    "не до",
    "не можна",
    "неабичим",
    "неабичого",
    "неабичому",
    "неабищо",
    "небагато",
    "небагатьма",
    "небагатьом",
    "небагатьох",
    "небудь",
    "невважаючи",
    "невже",
    "недалеко",
    "недалеко від",
    "неж",
    "незалежно від",
    "незважаючи",
    "незважаючи на",
    "ней",
    "немає",
    "немов",
    "немовби",
    "немовбито",
    "неначе",
    "неначебто",
    "неподалеку",
    "неподалеку від",
    "неподалечку",
    "неподалечку від",
    "неподалік",
    "неподалік від",
    "нерідко",
    "нех",
    "нехай",
    "нещодавно",
    "нею",
    "неї",
    "нижче",
    "низько",
    "ник",
    "ним",
    "ними",
    "них",
    "нич",
    "но",
    "ну",
    "нуг",
    "нуд",
    "нум",
    "нумо",
    "нумте",
    "ньо",
    "нього",
    "ньому",
    "ню",
    "нюх",
    "ня",
    "няв",
    "ні",
    "ніби",
    "ніби-то",
    "нібито",
    "ніде",
    "ніж",
    "нізащо",
    "нізвідки",
    "нізвідкіля",
    "ній",
    "ніким",
    "нікого",
    "нікогісінько",
    "ніколи",
    "нікому",
    "нікотра",
    "нікотре",
    "нікотрий",
    "нікотрим",
    "нікотрими",
    "нікотрих",
    "нікотрого",
    "нікотрому",
    "нікотрою",
    "нікотрої",
    "нікотру",
    "нікотрі",
    "нікотрій",
    "нікотрім",
    "нікуди",
    "нім",
    "нінащо",
    "ніскільки",
    "ніт",
    "ніхто",
    "нічий",
    "нічийна",
    "нічийне",
    "нічийний",
    "нічийним",
    "нічийними",
    "нічийних",
    "нічийного",
    "нічийному",
    "нічийною",
    "нічийної",
    "нічийну",
    "нічийні",
    "нічийній",
    "нічийнім",
    "нічийого",
    "нічийому",
    "нічим",
    "нічию",
    "нічия",
    "нічиє",
    "нічиєму",
    "нічиєю",
    "нічиєї",
    "нічиї",
    "нічиїй",
    "нічиїм",
    "нічиїми",
    "нічиїх",
    "нічого",
    "нічому",
    "ніщо",
    "ніяк",
    "ніяка",
    "ніяке",
    "ніякий",
    "ніяким",
    "ніякими",
    "ніяких",
    "ніякого",
    "ніякому",
    "ніякою",
    "ніякої",
    "ніяку",
    "ніякі",
    "ніякій",
    "ніякім",
    "ніякісінька",
    "ніякісіньке",
    "ніякісінький",
    "ніякісіньким",
    "ніякісінькими",
    "ніякісіньких",
    "ніякісінького",
    "ніякісінькому",
    "ніякісінькою",
    "ніякісінької",
    "ніякісіньку",
    "ніякісінькі",
    "ніякісінькій",
    "ніякісінькім",
    "о",
    "об",
    "обабіч",
    "обаполи",
    "обидва",
    "обр",
    "обік",
    "обіруч",
    "обіч",
    "ов",
    "од",
    "один",
    "одинадцятий",
    "одинадцять",
    "одна",
    "однак",
    "одначе",
    "одне",
    "одним",
    "одними",
    "одних",
    "одно",
    "одного",
    "одного разу",
    "одному",
    "одною",
    "одної",
    "одну",
    "одні",
    "одній",
    "однім",
    "однією",
    "однієї",
    "ож",
    "ой",
    "окрай",
    "окроме",
    "округ",
    "округи",
    "окрім",
    "окіл",
    "ом",
    "он",
    "онде",
    "онно",
    "оно",
    "оподаль",
    "оподаль від",
    "оподалік",
    "оподалік від",
    "опостін",
    "опостінь",
    "опроче",
    "опріч",
    "опріче",
    "опісля",
    "осе",
    "оскільки",
    "особливо",
    "осторонь",
    "ось",
    "осісьо",
    "от",
    "ота",
    "отак",
    "отака",
    "отаке",
    "отакий",
    "отаким",
    "отакими",
    "отаких",
    "отакого",
    "отакому",
    "отакою",
    "отакої",
    "отаку",
    "отакі",
    "отакій",
    "отакім",
    "отакісінька",
    "отакісіньке",
    "отакісінький",
    "отакісіньким",
    "отакісінькими",
    "отакісіньких",
    "отакісінького",
    "отакісінькому",
    "отакісінькою",
    "отакісінької",
    "отакісіньку",
    "отакісінькі",
    "отакісінькій",
    "отакісінькім",
    "отам",
    "оте",
    "отже",
    "отим",
    "отими",
    "отих",
    "ото",
    "отого",
    "отож",
    "отой",
    "отому",
    "отою",
    "отої",
    "отсе",
    "оттак",
    "отто",
    "оту",
    "отут",
    "оті",
    "отій",
    "отім",
    "отією",
    "отієї",
    "ох",
    "оце",
    "оцей",
    "оцим",
    "оцими",
    "оцих",
    "оцього",
    "оцьому",
    "оцю",
    "оця",
    "оці",
    "оцій",
    "оцім",
    "оцією",
    "оцієї",
    "п",
    "п'я",
    "п'ятий",
    "п'ятнадцятий",
    "п'ятнадцять",
    "п'ять",
    "па",
    "пад",
    "пак",
    "пек",
    "перед",
    "передо",
    "переді",
    "перетака",
    "перетаке",
    "перетакий",
    "перетаким",
    "перетакими",
    "перетаких",
    "перетакого",
    "перетакому",
    "перетакою",
    "перетакої",
    "перетаку",
    "перетакі",
    "перетакій",
    "перетакім",
    "перший",
    "пиж",
    "плі",
    "по",
    "поблизу",
    "побік",
    "побіля",
    "побіч",
    "поверх",
    "повз",
    "повздовж",
    "повинно",
    "повище",
    "повсюди",
    "повсюдно",
    "подаль від",
    "подалі від",
    "подекуди",
    "подеяка",
    "подеяке",
    "подеякий",
    "подеяким",
    "подеякими",
    "подеяких",
    "подеякого",
    "подеякому",
    "подеякою",
    "подеякої",
    "подеяку",
    "подеякі",
    "подеякій",
    "подеякім",
    "подовж",
    "подібно до",
    "поз",
    "поза",
    "позад",
    "позаду",
    "позата",
    "позате",
    "позатим",
    "позатими",
    "позатих",
    "позатого",
    "позатой",
    "позатому",
    "позатою",
    "позатої",
    "позату",
    "позаті",
    "позатій",
    "позатім",
    "позатією",
    "позатієї",
    "позаяк",
    "поздовж",
    "поки",
    "покрай",
    "покіль",
    "помежи",
    "помимо",
    "поміж",
    "помість",
    "понад",
    "понадо",
    "понаді",
    "понижче",
    "пообіч",
    "поодаль від",
    "поодалік від",
    "поперед",
    "попереду",
    "поперек",
    "попліч",
    "попри",
    "попросту",
    "попід",
    "пора",
    "поруч",
    "поряд",
    "поряд з",
    "порівняно з",
    "посеред",
    "посередині",
    "потрібно",
    "потім",
    "поуз",
    "початку",
    "почерез",
    "праворуч від",
    "пред",
    "предо",
    "преді",
    "прекрасно",
    "прецінь",
    "при",
    "притому",
    "причому",
    "причім",
    "про",
    "проз",
    "промеж",
    "проміж",
    "просто",
    "проте",
    "проти",
    "против",
    "противно",
    "протягом",
    "пря",
    "пріч",
    "пхе",
    "пху",
    "пі",
    "пів",
    "півперек",
    "під",
    "під знаком",
    "під приводом",
    "під час",
    "підо",
    "пізніше",
    "пім",
    "пір",
    "після",
    "р",
    "ради",
    "раз",
    "разом з",
    "разу",
    "рано",
    "раніш",
    "раніш від",
    "раніше",
    "раніше від",
    "раптом",
    "ре",
    "рет",
    "риж",
    "рим",
    "рип",
    "роб",
    "року",
    "років",
    "рос",
    "рох",
    "році",
    "рус",
    "рух",
    "руч",
    "рік",
    "с",
    "саж",
    "саз",
    "сак",
    "сам",
    "сама",
    "саме",
    "сами",
    "самий",
    "самим",
    "самими",
    "самих",
    "само",
    "самого",
    "самому",
    "самою",
    "самої",
    "саму",
    "самі",
    "самій",
    "самім",
    "сап",
    "сас",
    "свого",
    "свою",
    "своя",
    "своє",
    "своєму",
    "своєю",
    "своєї",
    "свої",
    "своїй",
    "своїм",
    "своїми",
    "своїх",
    "свій",
    "се",
    "себе",
    "себто",
    "сей",
    "сен",
    "серед",
    "середи",
    "середу",
    "сеч",
    "си",
    "сив",
    "сиг",
    "сиз",
    "сик",
    "сиріч",
    "сих",
    "сказав",
    "сказала",
    "сказати",
    "скрізь",
    "скільки",
    "скільки-то",
    "скількись",
    "скільком",
    "скількома",
    "скількомась",
    "скількомось",
    "скількомсь",
    "скількох",
    "скількохось",
    "скількохсь",
    "сли",
    "слідом за",
    "соб",
    "собою",
    "собі",
    "соп",
    "спасибі",
    "спереду",
    "спочатку",
    "справ",
    "справді",
    "став",
    "стосовно",
    "стільки",
    "стільком",
    "стількома",
    "стількох",
    "су",
    "судячи з",
    "супроти",
    "супротив",
    "суть",
    "суч",
    "суш",
    "сьогодні",
    "сьомий",
    "сюди",
    "ся",
    "сяг",
    "сяк",
    "сяка",
    "сяке",
    "сякий",
    "сяким",
    "сякими",
    "сяких",
    "сякого",
    "сякому",
    "сякою",
    "сякої",
    "сяку",
    "сякі",
    "сякій",
    "сякім",
    "сям",
    "сі",
    "сім",
    "сімнадцятий",
    "сімнадцять",
    "сіп",
    "т",
    "та",
    "таж",
    "так",
    "така",
    "таке",
    "такенна",
    "такенне",
    "такенний",
    "такенним",
    "такенними",
    "такенних",
    "такенного",
    "такенному",
    "такенною",
    "такенної",
    "такенну",
    "такенні",
    "такенній",
    "такеннім",
    "таки",
    "такий",
    "таким",
    "такими",
    "таких",
    "такого",
    "також",
    "такому",
    "такою",
    "такої",
    "таку",
    "такі",
    "такій",
    "такім",
    "такісінька",
    "такісіньке",
    "такісінький",
    "такісіньким",
    "такісінькими",
    "такісіньких",
    "такісінького",
    "такісінькому",
    "такісінькою",
    "такісінької",
    "такісіньку",
    "такісінькі",
    "такісінькій",
    "такісінькім",
    "тал",
    "там",
    "тамки",
    "тамта",
    "тамте",
    "тамтим",
    "тамтими",
    "тамтих",
    "тамтого",
    "тамтой",
    "тамтому",
    "тамтою",
    "тамтої",
    "тамту",
    "тамті",
    "тамтій",
    "тамтім",
    "тамтією",
    "тамтієї",
    "тар",
    "тат",
    "таш",
    "тва",
    "твого",
    "твою",
    "твоя",
    "твоє",
    "твоєму",
    "твоєю",
    "твоєї",
    "твої",
    "твоїй",
    "твоїм",
    "твоїми",
    "твоїх",
    "твій",
    "те",
    "тебе",
    "тег",
    "теж",
    "тем",
    "тепер",
    "теперечки",
    "тес",
    "теф",
    "теє",
    "ти",
    "тик",
    "тил",
    "тим",
    "тими",
    "тисяч",
    "тих",
    "то",
    "тобою",
    "тобто",
    "тобі",
    "того",
    "тоді",
    "тож",
    "той",
    "тол",
    "тому",
    "тому що",
    "тот",
    "тощо",
    "тою",
    "тої",
    "тра",
    "тре",
    "треба",
    "третій",
    "три",
    "тринадцятий",
    "тринадцять",
    "трохи",
    "тс",
    "тсс",
    "ту",
    "туди",
    "тудою",
    "туп",
    "тут",
    "тутеньки",
    "тутечки",
    "тутки",
    "туф",
    "туц",
    "тю",
    "тюг",
    "тюп",
    "тяг",
    "тяж",
    "тям",
    "тяп",
    "ті",
    "тій",
    "тільки",
    "тім",
    "тією",
    "у",
    "у бік",
    "у вигляді",
    "у випадку",
    "у відповідності до",
    "у відповідь на",
    "у залежності від",
    "у зв'язку з",
    "у міру",
    "у напрямі до",
    "у порівнянні з",
    "у процесі",
    "у результаті",
    "у ролі",
    "у силу",
    "у сторону",
    "у супроводі",
    "у ході",
    "ув",
    "увесь",
    "уві",
    "угу",
    "уже",
    "узбіч",
    "уздовж",
    "укр",
    "ум",
    "унаслідок",
    "униз",
    "унизу",
    "унт",
    "уперед",
    "уподовж",
    "упоперек",
    "упритиск до",
    "упритул до",
    "упродовж",
    "упрост",
    "ус",
    "усе",
    "усередині",
    "услід",
    "услід за",
    "усупереч",
    "усього",
    "усьому",
    "усю",
    "усюди",
    "уся",
    "усяк",
    "усяка",
    "усяке",
    "усякий",
    "усяким",
    "усякими",
    "усяких",
    "усякого",
    "усякому",
    "усякою",
    "усякої",
    "усяку",
    "усякі",
    "усякій",
    "усякім",
    "усі",
    "усій",
    "усіляка",
    "усіляке",
    "усілякий",
    "усіляким",
    "усілякими",
    "усіляких",
    "усілякого",
    "усілякому",
    "усілякою",
    "усілякої",
    "усіляку",
    "усілякі",
    "усілякій",
    "усілякім",
    "усім",
    "усіма",
    "усіх",
    "усією",
    "усієї",
    "утім",
    "ух",
    "ф",
    "ф'ю",
    "фа",
    "фаг",
    "фай",
    "фат",
    "фе",
    "фед",
    "фез",
    "фес",
    "фет",
    "фзн",
    "фоб",
    "фот",
    "фра",
    "фру",
    "фу",
    "фук",
    "фур",
    "фус",
    "фіш",
    "х",
    "ха",
    "хаз",
    "хай",
    "хап",
    "хат",
    "хащ",
    "хе",
    "хет",
    "хи",
    "хиб",
    "хм",
    "хо",
    "хов",
    "хол",
    "хон",
    "хоп",
    "хор",
    "хотіти",
    "хоч",
    "хоча",
    "хочеш",
    "хро",
    "хрю",
    "хто",
    "хтось",
    "ху",
    "хуз",
    "хук",
    "хух",
    "хху",
    "хіба",
    "ц",
    "це",
    "цебто",
    "цей",
    "цеп",
    "ци",
    "цим",
    "цими",
    "цир",
    "цих",
    "цло",
    "цоб",
    "цок",
    "цоп",
    "цор",
    "цс",
    "цсс",
    "цуг",
    "цур",
    "цуц",
    "цього",
    "цьому",
    "цю",
    "цюк",
    "ця",
    "цяв",
    "цяп",
    "ці",
    "цід",
    "цій",
    "цім",
    "ціною",
    "цією",
    "цієї",
    "ч",
    "чал",
    "чар",
    "час",
    "часто",
    "частіше",
    "часу",
    "чах",
    "чей",
    "чень",
    "через",
    "четвертий",
    "чи",
    "чий",
    "чийого",
    "чийогось",
    "чийому",
    "чийомусь",
    "чийсь",
    "чик",
    "чим",
    "чимось",
    "чимсь",
    "чир",
    "численна",
    "численне",
    "численний",
    "численним",
    "численними",
    "численних",
    "численні",
    "чию",
    "чиюсь",
    "чия",
    "чиясь",
    "чиє",
    "чиєму",
    "чиємусь",
    "чиєсь",
    "чиєю",
    "чиєюсь",
    "чиєї",
    "чиєїсь",
    "чиї",
    "чиїй",
    "чиїйсь",
    "чиїм",
    "чиїми",
    "чиїмись",
    "чиїмось",
    "чиїмсь",
    "чиїсь",
    "чиїх",
    "чиїхось",
    "чиїхсь",
    "чля",
    "чого",
    "чогось",
    "чом",
    "чому",
    "чомусь",
    "чон",
    "чоп",
    "чортзна",
    "чос",
    "чотири",
    "чотирнадцятий",
    "чотирнадцять",
    "чу",
    "чум",
    "чур",
    "чш",
    "чім",
    "чімось",
    "чімсь",
    "чіт",
    "ш",
    "ша",
    "шаг",
    "шал",
    "шам",
    "шво",
    "шед",
    "шен",
    "шиз",
    "шир",
    "шляхом",
    "шостий",
    "шістнадцятий",
    "шістнадцять",
    "шість",
    "щ",
    "ще",
    "щем",
    "щеп",
    "щип",
    "щир",
    "що",
    "щоб",
    "щоби",
    "щодо",
    "щойно",
    "щоправда",
    "щось",
    "щі",
    "ь",
    "ю",
    "юз",
    "юн",
    "юнь",
    "юс",
    "ют",
    "юхт",
    "я",
    "яв",
    "яд",
    "яз",
    "язь",
    "як",
    "яка",
    "якась",
    "якби",
    "яке",
    "якесь",
    "який",
    "якийсь",
    "яким",
    "якими",
    "якимись",
    "якимось",
    "якимсь",
    "яких",
    "якихось",
    "якихсь",
    "якого",
    "якогось",
    "якому",
    "якомусь",
    "якось",
    "якою",
    "якоюсь",
    "якої",
    "якоїсь",
    "якраз",
    "яку",
    "якусь",
    "якщо",
    "які",
    "якій",
    "якійсь",
    "якім",
    "якімсь",
    "якісь",
    "ял",
    "ям",
    "ян",
    "янь",
    "яо",
    "яп",
    "ярл",
    "ясь",
    "ять",
    "є",
    "єр",
    "єси",
    "і",
    "ібн",
    "ід",
    "із",
    "із-за",
    "із-під",
    "іззаду",
    "ізм",
    "ізсередини",
    "ік",
    "ікс",
    "ікт",
    "ім'я",
    "імовірно",
    "інакша",
    "інакше",
    "інакший",
    "інакшим",
    "інакшими",
    "інакших",
    "інакшого",
    "інакшому",
    "інакшою",
    "інакшої",
    "інакшу",
    "інакші",
    "інакшій",
    "інакшім",
    "інколи",
    "іноді",
    "інша",
    "інше",
    "інший",
    "іншим",
    "іншими",
    "інших",
    "іншого",
    "іншому",
    "іншою",
    "іншої",
    "іншу",
    "інші",
    "іншій",
    "іншім",
    "інь",
    "іч",
    "іще",
    "ї",
    "їдь",
    "їй",
    "їм",
    "їх",
    "їхнього",
    "їхньому",
    "їхньою",
    "їхньої",
    "їхню",
    "їхня",
    "їхнє",
    "їхні",
    "їхній",
    "їхнім",
    "їхніми",
    "їхніх",
    "її",
    "ґ",
]


def sanitize_tantivy_query(query: str, rate=0) -> str:
    """Remove special chars and reduce Ukrainian words to their root form."""
    # 1. Remove Tantivy special syntax chars and Ukrainian apostrophes
    # Note: We keep spaces to separate words for the lemmatizer
    cleaned = re.sub(r"""[+\-&|!(){}\[\]^"~*?:\\/\u2019\u02BC']""", " ", query)
    # 2. Tokenize and Lemmatize
    # We split the cleaned string, get the normal form of each word, and join back
    words = cleaned.lower().split()

    # 3. Remove stopwords:
    words = [word for word in words if word not in UK_STOP_WORDS]

    if rate > 0:
        cutoff = np.max([1, int(len(words) * rate)])
        words = words[cutoff:]
    lemmatized_words = [morph.parse(word)[0].normal_form for word in words]
    # 3. Collapse multiple spaces and join
    final_query = " ".join(lemmatized_words).strip()
    return final_query

In [13]:
def search_embeddings(queries_embeddings, documents_embeddings, K=1):
    n_docs = len(documents_embeddings)
    # 1. Cap K to the total number of documents available
    K = min(K, n_docs)
    similarity_matrix = queries_embeddings @ documents_embeddings.T
    # 2. Handle the K boundary for argpartition
    if K < n_docs:
        # Standard partial sort
        topk_doc_ids = np.argpartition(-similarity_matrix, K, axis=1)[:, :K]
    else:
        # If K is the total size, just take everything (indices 0 to n_docs-1)
        topk_doc_ids = np.tile(np.arange(n_docs), (len(queries_embeddings), 1))
    # 3. Sort the results (identical to your original logic)
    topk_scores = np.take_along_axis(similarity_matrix, topk_doc_ids, axis=1)
    sorted_idx = np.argsort(-topk_scores, axis=1)

    topk_doc_ids = np.take_along_axis(topk_doc_ids, sorted_idx, axis=1)
    topk_scores = np.take_along_axis(topk_scores, sorted_idx, axis=1)

    return topk_doc_ids, topk_scores

In [14]:
%%writefile pdf_worker.py
import os
import sys
import json
import argparse
import pymupdf
import pymupdf4llm 

def _sanitize_output(data):
    """Recursively convert non-JSON serializable MuPDF objects to basic types."""
    if isinstance(data, dict):
        return {k: _sanitize_output(v) for k, v in data.items()}
    elif isinstance(data, (list, tuple)):
        return [_sanitize_output(i) for i in data]
    # Check for MuPDF specific types (Rect, Point, IRect, etc.)
    elif hasattr(data, "__class__") and "pymupdf" in str(data.__class__):
        return list(data) if hasattr(data, "__iter__") else str(data)
    return data

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--path", required=True)
    parser.add_argument("--page", type=int, required=True)
    args = parser.parse_args()

    path = args.path
    pno = args.page

    try:
        doc = pymupdf.open(path)
        # We use a very restrictive extraction to avoid overhead
        result = pymupdf4llm.to_markdown(
            doc, 
            pages=[pno], 
            page_chunks=True,
            write_images=False,
            graphics_limit=0
        )
        # Ensure we have a dict
        data = result[0] if (isinstance(result, list) and len(result) > 0) else {}
        
    except Exception as e:
        try:
            doc = pymupdf.open(path)
            page = doc.load_page(pno)
            data = {
                'metadata': {'title': "FALLBACK", 'page': pno+1, 'file_path': path}, 
                'text': page.get_text("text")
            }
        except Exception:
            data = {
                'metadata': {'title': "FAILED", 'page': pno+1, "file_path": path},
                'text': ""
            }

    # The sanitization now handles the 'Rect' objects that caused your crash
    print(json.dumps(_sanitize_output(data)))

Writing pdf_worker.py

In [15]:
from concurrent.futures import ThreadPoolExecutor, as_completed
import json
import subprocess
import sys

import pymupdf
from tqdm.notebook import tqdm


def load_pdf_with_hard_timeouts(path, num_workers=4, page_timeout=15):
    doc = pymupdf.open(path)
    total_pages = len(doc)
    doc.close()

    full_md_output = [None] * total_pages

    def extract_page_via_subprocess(pno):
        cmd = [sys.executable, "pdf_worker.py", "--path", path, "--page", str(pno)]

        try:
            proc = subprocess.run(cmd, capture_output=True, text=True, timeout=page_timeout)

            if proc.returncode == 0 and proc.stdout.strip():
                # CRITICAL FIX: Ignore library warnings printed to stdout.
                # Only grab the very last line where our JSON is printed.
                raw_output = proc.stdout.strip()
                last_line = raw_output.split("\n")[-1]

                try:
                    return pno, json.loads(last_line)
                except json.JSONDecodeError:
                    # If it's still not JSON, return the raw terminal output so you can debug it
                    error_msg = f"Invalid Output format.\nSTDOUT:\n{raw_output}\nSTDERR:\n{proc.stderr}"
                    print(f"Error (1): page number {pno}")
                    return pno, {"text": error_msg, "metadata": {"page": pno + 1, "file_path": path}}
            else:
                # If the script crashed entirely, show the standard error
                error_msg = f"Worker Crashed. Return Code: {proc.returncode}\nSTDERR:\n{proc.stderr}"
                print(f"Error (2): page number {pno}")
                return pno, {"text": error_msg, "metadata": {"page": pno + 1, "file_path": path}}

        except subprocess.TimeoutExpired:
            print(f"Error (timeout): page number {pno}")
            return pno, {"text": "Timeout.", "metadata": {"title": "TIMEOUT", "page": pno + 1, "file_path": path}}
        except Exception as e:
            print(f"Error (unknown): page number {pno}")
            return pno, {"text": f"Unexpected Error: {str(e)}", "metadata": {"page": pno + 1, "file_path": path}}

    with ThreadPoolExecutor(max_workers=num_workers) as executor:
        futures = {executor.submit(extract_page_via_subprocess, pno): pno for pno in range(total_pages)}

        for future in tqdm(as_completed(futures), total=total_pages, desc="Extracting Pages"):
            pno = futures[future]
            full_md_output[pno] = future.result()[1]

    return full_md_output


def process_md_page(page):
    try:
        page_n = page["metadata"]["page_number"]
    except:
        page_n = page["metadata"]["page"]
    return {
        "page_number": page_n,
        "doc_id": page["metadata"]["file_path"].split("/")[-1],
        "full_text": page.get("text", ""),
        "doc_title": page["metadata"].get("title", ""),
    }

# Loading documents:

In [16]:
# Getting all files:
import sys

from tqdm import tqdm

data_files = glob.glob(DATA_PATH)
print("Number of files found:", len(data_files))
file_path_to_id = {file_path: file_path.split("/")[-1] for file_path in data_files}
all_parsed_domains = {file_path.split("/")[-1]: file_path.split("/")[-2] for file_path in data_files}
# Parsing all documents:
all_parsed = {}
for i, fp in enumerate(data_files):
    print(i + 1, fp)
    parsed = load_pdf_with_hard_timeouts(fp)
    all_parsed[file_path_to_id[fp]] = [process_md_page(page) for page in parsed]

Number of files found: 2
1 /kaggle/input/competitions/unlp-2026-shared-task-on-multi-domain-document-understanding/test/domain_1/759dfc8486c0f02391d7cfc1fed753b0608fc601.pdf

Extracting Pages: 100%|██████████| 79/79 [00:17<00:00,  4.48it/s]

2 /kaggle/input/competitions/unlp-2026-shared-task-on-multi-domain-document-understanding/test/domain_2/aba537442395c1a4ca13d05e378a49a47865cc46.pdf

Extracting Pages: 100%|██████████| 20/20 [00:02<00:00,  7.35it/s]

In [17]:
input_df = pd.read_csv(TRAIN_PATH)
print(len(input_df))
input_df.head(2)

2

   Question_ID                                         Question                                         A                                                  B                                C                                           D                                                  E                                                  F
0            0  Що означає термін «у грі» на змаганнях з регбі?  гравця позначили маленькою позначкою 'X'  гравець перебуває в положенні, що дає можливіс...  гравець перетнув лінію вкидання  гравець покараний за положення «поза грою»  удар ногою, призначений на користь невинної в ...  гравець опинився ближче 10-ти метрів від супер...
1            4            Як слід приймати препарат максифлокс?                 вводити внутрішньом'язово                                 вводити вагінально                 приймати орально                     вводити внутрішньовенно                                  натирати на шкіру                                  вводити ректально

In [18]:
import glob
import sys

data_files = glob.glob(DOMAIN_PATH)
print("Number of files found:", len(data_files))
file_path_to_id = {file_path: file_path.split("/")[-2] for file_path in data_files}


def extract_document_info(filepath: str) -> dict:
    """
    Reads a standardized text file and extracts:
    1. The first sentence.
    2. A list of bulleted items.
    """
    try:
        with open(filepath, encoding="utf-8") as file:
            text = file.read().strip()
    except FileNotFoundError:
        return {"error": f"File not found at {filepath}"}

    # 1. Extract the first sentence
    # Matches any character except terminal punctuation, followed by the punctuation.
    first_sentence_match = re.match(r"([^.!?]+[.!?])", text)
    first_sentence = first_sentence_match.group(1).strip() if first_sentence_match else "No sentence found."

    # 2. Extract the list of items
    # ^\s*[-–—]\s* : Matches the start of a line, optional spaces, and a dash (handles different dash types).
    # (.+?)        : Captures the actual text of the bullet point.
    # [;.]?\s*$    : Ignores trailing semicolons or periods at the end of the line.
    list_items = []
    for match in re.finditer(r"^\s*[-–—]\s*(.+?)[;.]?\s*$", text, re.MULTILINE):
        list_items.append(match.group(1).strip())

    return {"first_sentence": first_sentence, "included_items": list_items, "full_text": text}


domains_metadata = {}
for path, domain in file_path_to_id.items():
    domains_metadata[domain] = extract_document_info(path)

Number of files found: 2

In [19]:
import builtins
import os

from transformers import AutoConfig, AutoModel

# 1. THE BYPASS: Temporarily override the 'input' function
# so when the library asks [y/N], the system automatically answers 'y'
original_input = builtins.input
builtins.input = lambda _: "y"

MODEL_PATH = "/kaggle/input/models/trokhymovych/perplexity-context/transformers/default/1/pplx06-model-context"

# 2. Set strict offline flags
os.environ["TRANSFORMERS_OFFLINE"] = "1"
os.environ["HF_HUB_TRUST_REMOTE_CODE"] = "1"

try:
    print("Attempting silent load...")

    # 3. Load Config
    config = AutoConfig.from_pretrained(MODEL_PATH, trust_remote_code=True, local_files_only=True)

    # 4. Load Model
    model_ctx = AutoModel.from_pretrained(
        MODEL_PATH,
        config=config,
        trust_remote_code=True,
        local_files_only=True,
        torch_dtype=torch.bfloat16,
    ).to("cuda")

    print("Success! Model loaded to CUDA.")

finally:
    # 5. RESTORE the original input function so the rest of your notebook works
    builtins.input = original_input


def embed_any(inputs, model_ctx=model_ctx, batch_size=4, show_progress_bar=True):
    """
    Normalizes input into List[List[str]] for model_ctx.encode(),
    then restores output structure.

    Input cases:
    - str → [[str]] → returns np.ndarray (1, dim) → squeezed to (dim,)
    - List[str] → [[str], [str], ...] → returns List[np.ndarray]
    - List[List[str]] → unchanged → returns List[np.ndarray]

    Returns:
    - single embedding (1D array) OR
    - list of embeddings OR
    - list of arrays (contextual chunks)
    """

    # Case 1: single string
    if isinstance(inputs, str):
        normalized = [[inputs]]
        single_input = True
        flat_list = False

    # Case 2: list of strings
    elif isinstance(inputs, list) and all(isinstance(x, str) for x in inputs):
        normalized = [[x] for x in inputs]
        single_input = False
        flat_list = True

    # Case 3: list of list of strings
    elif (
        isinstance(inputs, list)
        and all(isinstance(x, list) for x in inputs)
        and all(all(isinstance(s, str) for s in x) for x in inputs)
    ):
        normalized = inputs
        single_input = False
        flat_list = False
        # raise ValueError("Unsupported input format")
    else:
        raise ValueError("Unsupported input format")

    # Encode
    embeddings = model_ctx.encode(
        normalized, batch_size=batch_size, show_progress_bar=show_progress_bar, normalize_embeddings=True
    )

    # Restore structure
    if single_input:
        # embeddings[0] shape: (1, dim) → return (dim,)
        return embeddings[0][0]

    if flat_list:
        # each embeddings[i] is (1, dim) → return list of (dim,)
        return [emb[0] for emb in embeddings]

    # already contextual → return as-is
    return embeddings


def embed_with_sliding_window(texts, model_ctx=model_ctx, window_size=4, stride=2, show_progress_bar=True):
    """
    Creates overlapping windows to preserve context,
    then averages embeddings for items appearing in multiple windows.
    """
    n = len(texts)
    # Dictionary to store list of embeddings for each index
    # (since an index might appear in multiple windows)
    index_to_embeddings = {i: [] for i in range(n)}

    # 1. Generate Windows
    windows = []
    window_indices = []

    for start in range(0, n, stride):
        end = start + window_size
        subset = texts[start:end]
        if not subset:
            break
        windows.append(subset)
        window_indices.append(list(range(start, min(end, n))))

        # Stop if we've reached the end
        if end >= n:
            break

    # 2. Encode all windows (model_ctx handles the internal List[List[str]] logic)
    # We use a small batch_size here to keep VRAM low
    all_window_outputs = model_ctx.encode(
        windows, batch_size=1, normalize_embeddings=True, show_progress_bar=show_progress_bar
    )

    # 3. Map embeddings back to original indices
    # all_window_outputs is a list of arrays, where each array is (window_len, dim)
    for window_idx_list, window_emb in zip(window_indices, all_window_outputs, strict=False):
        for local_i, global_i in enumerate(window_idx_list):
            index_to_embeddings[global_i].append(window_emb[local_i])

    # 4. Average the overlaps (to get one vector per text item)
    final_embeddings = []
    for i in range(n):
        combined = np.mean(index_to_embeddings[i], axis=0)
        # Re-normalize after averaging
        final_embeddings.append(combined / np.linalg.norm(combined))

    return np.array(final_embeddings)

Attempting silent load...

Loading weights:   0%|          | 0/310 [00:00<?, ?it/s]

Success! Model loaded to CUDA.

In [20]:
from transformers import AutoModel

reranker = AutoModel.from_pretrained(
    "/kaggle/input/models/aaryanverma/jina-reranker-v3/transformers/default/1/jina-reranker-v3",
    dtype="auto",
    trust_remote_code=True,
    local_files_only=True,
    tie_word_embeddings=False,
).to("cuda")
reranker.eval()

Loading weights:   0%|          | 0/312 [00:00<?, ?it/s]

JinaForRanking(
  (model): Qwen3Model(
    (embed_tokens): Embedding(151936, 1024)
    (layers): ModuleList(
      (0-27): 28 x Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear(in_features=1024, out_features=2048, bias=False)
          (k_proj): Linear(in_features=1024, out_features=1024, bias=False)
          (v_proj): Linear(in_features=1024, out_features=1024, bias=False)
          (o_proj): Linear(in_features=2048, out_features=1024, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=1024, out_features=3072, bias=False)
          (up_proj): Linear(in_features=1024, out_features=3072, bias=False)
          (down_proj): Linear(in_features=3072, out_features=1024, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen3RMSNorm((1024,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((1024,), eps=1e-06)
      )
    )
    (norm): Qwen3RMSNorm((1024,), eps=1e-06)
    (rotary_emb): Qwen3RotaryEmbedding()
  )
  (lm_head): Identity()
  (projector): Sequential(
    (0): Linear(in_features=1024, out_features=512, bias=False)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=False)
  )
)

# Domain parsing:

In [21]:
@dataclass
class Domain:
    domain_id: str
    domain_text: str
    domain_embedding: np.ndarray
    domain_list: list[str]
    domain_list_embeddings: np.ndarray


domains = []
for key, value in tqdm(domains_metadata.items()):
    domains.append(
        Domain(
            domain_id=key,
            domain_text=value["first_sentence"],
            domain_embedding=embed_any(value["first_sentence"] + " ".join(value["included_items"])),
            domain_list=value["included_items"],
            domain_list_embeddings=embed_any(value["included_items"]),
        )
    )

from scipy import spatial

domain_dict = {d.domain_id: d for d in domains}


# Build domain scoring function:
def get_domain_similarity(query_emb, text_emb, domain):
    domain_embeddings = np.array(domain_dict[domain].domain_list_embeddings)
    dataSetI = domain_embeddings.dot(query_emb)
    dataSetII = domain_embeddings.dot(text_emb)
    similarity = 1 - spatial.distance.cosine(dataSetI, dataSetII)
    return similarity

  0%|          | 0/2 [00:00<?, ?it/s]
Encoding documents:   0%|          | 0/1 [00:00<?, ?it/s]
Encoding documents: 100%|██████████| 1/1 [00:00<00:00,  1.23it/s]

Encoding documents:   0%|          | 0/4 [00:00<?, ?it/s]
Encoding documents:  50%|█████     | 2/4 [00:00<00:00, 12.39it/s]
Encoding documents: 100%|██████████| 4/4 [00:00<00:00, 12.75it/s]
 50%|█████     | 1/2 [00:01<00:01,  1.14s/it]
Encoding documents:   0%|          | 0/1 [00:00<?, ?it/s]
Encoding documents: 100%|██████████| 1/1 [00:00<00:00,  6.98it/s]

Encoding documents:   0%|          | 0/4 [00:00<?, ?it/s]
Encoding documents:  50%|█████     | 2/4 [00:00<00:00, 10.50it/s]
Encoding documents: 100%|██████████| 4/4 [00:00<00:00, 11.15it/s]
100%|██████████| 2/2 [00:01<00:00,  1.21it/s]

## Queries Preparation:

In [22]:
@dataclass
class QueryParsed:
    question_id: int
    question_text: str
    question_text_short_half: str
    question_options: list[str]
    # question_text_embedding: np.ndarray
    # question_options_embeddings: np.ndarray
    question_text_all_options_embeddings: np.ndarray
    # question_text_sep_options_embeddings: np.ndarray
    predicted_domain: str
    predicted_domain_issue: str
    predicted_domain_issue_emb: np.ndarray


queries = []
for _, row in tqdm(input_df.iterrows(), total=len(input_df)):
    query = row["Question"]
    options = row[["A", "B", "C", "D", "E", "F"]].values.tolist()
    # Replace NaN with empty string to avoid embedding issues
    options = [str(o) if pd.notna(o) else "" for o in options]
    options_non_empty = [o for o in options if o]  # filter blanks for embedding

    queries.append(
        QueryParsed(
            question_id=row["Question_ID"],
            question_text=query,
            question_text_short_half=sanitize_tantivy_query(query, rate=0.5),
            question_options=options,
            question_text_all_options_embeddings=None,
            predicted_domain=None,
            predicted_domain_issue=None,
            predicted_domain_issue_emb=None,
            # question_text_embedding = embed_any(query),
            # question_options_embeddings = embed_any(options_non_empty) if options_non_empty else embed_any([""]),
            # question_text_all_options_embeddings = embed_any(query + " ".join(options)),
            # question_text_sep_options_embeddings = embed_any([query + option for option in options]),
        )
    )
queries_texts = [q.question_text + " " + " ".join(q.question_options) for q in queries]
queries_embeddings = embed_any(queries_texts)

for q, emb in zip(queries, queries_embeddings, strict=False):
    q.question_text_all_options_embeddings = emb

100%|██████████| 2/2 [00:00<00:00, 285.86it/s]
Encoding documents: 100%|██████████| 1/1 [00:00<00:00,  9.03it/s]

In [23]:
# 1. Defining query domain:
domain_ids = [domain.domain_id for domain in domains]
domain_embs = np.array([domain.domain_embedding for domain in domains])
queries_embs = np.array([query.question_text_all_options_embeddings for query in queries])

selected_domain_ids, search_scores = search_embeddings(queries_embs, domain_embs, K=len(domain_ids))
selected_domain_names = [domain_ids[i[0]] for i in selected_domain_ids]

input_df["predicted_domain"] = selected_domain_names

# 2. Defining what is query about (related to domain):
selected_issues = []
for i, row in input_df.iterrows():
    selected_domain = row["predicted_domain"]
    selected_domain_metadata = [d for d in domains if d.domain_id == selected_domain][0]

    list_names = selected_domain_metadata.domain_list
    list_emb = np.array(selected_domain_metadata.domain_list_embeddings)

    selected_ids, _ = search_embeddings(
        np.array([queries[i].question_text_all_options_embeddings]), list_emb, K=len(list_emb)
    )
    selected_name = [list_names[i[0]] for i in selected_ids][0]
    selected_issues.append(selected_name)
input_df["predicted_issues"] = selected_issues

# Filling metadata for queries:
for i, row in input_df.iterrows():
    query = queries[i]
    predicted_domain = row["predicted_domain"]
    predicted_domain_issue = row["predicted_issues"]

    predicted_domain = [d for d in domains if d.domain_id == predicted_domain][0]

    predicted_domain_emb = predicted_domain.domain_embedding
    predicted_domain_issue_emb = [
        j
        for i, j in zip(predicted_domain.domain_list, predicted_domain.domain_list_embeddings, strict=False)
        if i == predicted_domain_issue
    ][0]

    query.predicted_domain = predicted_domain
    query.predicted_domain_issue = predicted_domain_issue
    query.predicted_domain_emb = predicted_domain_emb
    query.predicted_domain_issue_emb = predicted_domain_issue_emb

# Documents Preparation:

In [24]:
# from langchain_text_splitters import MarkdownHeaderTextSplitter
# from langchain_core.documents import Document


def remove_official_boilerplate(full_text):
    """
    Видаляє бюрократичні 'шапки', грифи затвердження та технічні підписи з тексту.
    """
    # 1. Видаляємо блок "ЗАТВЕРДЖУЮ ... ПІБ"
    # Шукає слово ЗАТВЕРДЖУЮ (в будь-якому регістрі), далі посади (Міністр, заступник тощо)
    # і вирізає все до моменту, поки не зустріне великий заголовок типу ПРАВИЛА, ІНСТРУКЦІЯ або #
    full_text = re.sub(
        r"(?i)ЗАТВЕРДЖУЮ[\s\S]{1,400}?(?=\n#|\n\*\*|ПРАВИЛА|ІНСТРУКЦІЯ|ПОЛОЖЕННЯ|ПОРЯДОК)", "", full_text
    )
    # 2. Видаляємо блоки "ПОГОДЖЕНО ... ПІБ" (часто бувають в кінці або на початку)
    full_text = re.sub(r"(?i)ПОГОДЖЕНО[\s\S]{1,400}?(?=\n\n|\n#)", "", full_text)

    # 3. Видаляємо технічні артефакти електронного документообігу (СЕД, КЕП)
    # Наприклад: "СЕД Megapolis.DocNet Міністерство молоді та спорту..."
    full_text = re.sub(r"(?i)СЕД Megapolis.*?(?=\n\n|\n#|$)", "", full_text, flags=re.DOTALL)

    # Видаляємо рядки з інформацією про КЕП (Кваліфікований електронний підпис) та його довгі хеш-коди
    full_text = re.sub(r"(?i)КЕП:.*?\n", "\n", full_text)
    full_text = re.sub(r"[A-F0-9]{30,}", "", full_text)  # Видаляє довгі 16-кові коди підпису

    # 4. Видаляємо зайві порожні рядки, які могли утворитися після очищення
    full_text = re.sub(r"\n{3,}", "\n\n", full_text)
    return full_text.strip()


def clean_for_search(text):
    """Посилене очищення: замінює HTML та символи таблиць на пробіли для запобігання злипленню слів."""

    # 0. Замінюємо HTML теги на ПРОБІЛ (щоб слова не злипалися)
    text = re.sub(r"<[^>]+>", " ", text)

    # 1. Видаляємо заглушки зображень
    text = re.sub(r"==>.*?<==", " ", text)

    # 2. Видаляємо Markdown таблиці:
    # Замінюємо роздільники (|---|) та окремі пайпи на пробіли
    text = re.sub(r"\|[\s\-\:|]+\|", " ", text)
    text = re.sub(r"\|", " ", text)

    # 3. Видаляємо форматування (bold/italic)
    text = re.sub(r"[\*_]{1,3}", "", text)

    # 4. Видаляємо хеші заголовків
    text = re.sub(r"#+\s+", " ", text)

    # 5. Видаляємо посилання [text](url) -> text
    text = re.sub(r"\[(.*?)\]\(.*?\)", r" \1 ", text)

    # 6. Видаляємо зворотні слеші
    text = re.sub(r"\\", "", text)

    # 7. ФІНАЛЬНИЙ КРОК: Замінюємо всі послідовності пробілів/переносів на ОДИН пробіл
    # Це прибере зайві пробіли, які ми створили вище
    text = re.sub(r"\s+", " ", text)

    try:
        text = remove_official_boilerplate(text.strip())
    except NameError:
        text = text.strip()

    return text

In [25]:
@dataclass
class DocumentParsed:
    document_name: str
    document_title: str
    pages_text: str
    document_embedding: np.ndarray
    document_pages: list[str]


documents = []
MAX_LEN = 300  # (We need only the first few words in reality....)
for k, v in tqdm(all_parsed.items()):
    # print(k, "\t\t\t Num pages:", len(v))
    document_texts = [page["full_text"] for page in v]
    document_texts = [doc for doc in document_texts if doc and len(doc) > 10]
    document_texts_clean = [clean_for_search(t) for t in document_texts]

    # Guard: skip documents with zero valid text pages
    if not document_texts:
        print(f"  WARNING: {k} has no valid text pages, using placeholder embedding")
        documents.append(
            DocumentParsed(
                document_name=k,
                document_title=" ",
                pages_text=" ",
                document_embedding=np.array([0] * 1024),
                document_pages=list[str],
                document_pages_embeddings=np.array([[0] * 1024]),
            )
        )
        continue

    document_content = clean_for_search(" ".join(document_texts))
    documents.append(
        DocumentParsed(
            document_name=k,
            document_title=v[0]["doc_title"],
            pages_text=document_content,
            document_embedding=None,
            document_pages=document_texts_clean,
        )
    )

# Calculating document embeddings:
documents_texts = [d.pages_text[:MAX_LEN] for d in documents]
documents_embeddings = embed_any(documents_texts)

for d, emb in zip(documents, documents_embeddings, strict=False):
    d.document_embedding = emb

100%|██████████| 2/2 [00:00<00:00, 23.31it/s]
Encoding documents: 100%|██████████| 1/1 [00:00<00:00,  9.08it/s]

# Document Search:

### Vector search

In [26]:
document_ids = [doc.document_name for doc in documents]
queries_embs = np.array([query.question_text_all_options_embeddings for query in queries])
documents_embs = np.array([doc.document_embedding for doc in documents])

selected_documents_ids, search_scores = search_embeddings(queries_embs, documents_embs, K=len(documents))
selected_documents_names = [document_ids[i[0]] for i in selected_documents_ids]
selected_documents_scores = [i[0] for i in search_scores]

input_df["Doc_ID_pred"] = selected_documents_names
input_df["Doc_ID_score"] = selected_documents_scores

if TRAIN:
    print("Document search accuracy: ", (input_df["Doc_ID_pred"] == input_df["Doc_ID"]).mean())

### Adding boost from lexical search: 
If the score for the semantical search is low -> add the lexical search boost.

In [27]:
def get_lexical_snippet(document_text, query, window_size=100, overlap=75):
    words = document_text.split()
    if len(words) <= window_size:
        return document_text
    segments = []
    for i in range(0, len(words), window_size - overlap):
        segment = words[i : i + window_size]
        if len(segment) > 5:  # Ignore tiny trailing fragments
            segments.append(segment)
    tokenized_corpus = [[w.lower().strip(".,!?;:()") for w in s] for s in segments]
    bm25 = BM25Okapi(tokenized_corpus)
    tokenized_query = query.lower().strip().split()
    best_segment = bm25.get_top_n(tokenized_query, segments, n=1)[0]
    return " ".join(best_segment)


def calculating_documets_boosts(query, corpus, doc_ids):
    def search(query):
        query = sanitize_tantivy_query(query)
        tokenized_query = query.lower().split(" ")
        doc_scores = corpus.get_scores(tokenized_query)
        return doc_scores

    scores = search(query)
    max_score = np.max(scores)
    if max_score == 0:
        return {doc_id: 0.0 for doc_id in doc_ids}
    score_boosts = {doc_id: s / max_score for doc_id, s in zip(doc_ids, scores, strict=False)}
    return score_boosts


def get_ranking(score_dict):
    # Sort by score descending
    sorted_docs = sorted(score_dict.items(), key=lambda item: item[1], reverse=True)
    # Return list of filenames in order
    return [doc[0] for doc in sorted_docs]


doc_domains = [domains_metadata[all_parsed_domains[doc.document_name]]["full_text"] for doc in documents]
corpus = [
    sanitize_tantivy_query(domain_text + " " + doc.pages_text + " " + doc.document_title)
    for doc, domain_text in zip(documents, doc_domains, strict=False)
    # sanitize_tantivy_query(doc.pages_text) for doc in documents  # We should prepare the query the same as the text
]

tokenized_corpus = [doc.lower().split(" ") for doc in corpus]
bm25 = BM25Okapi(tokenized_corpus)

### Lexical Boosts:
document_ids = [doc.document_name for doc in documents]
lexical_score_boosts = []
for query in tqdm(queries):
    score_boost = calculating_documets_boosts(query.question_text, bm25, document_ids)
    lexical_score_boosts.append(score_boost)

### Vector Boosts:
selected_documents_ids, search_scores = search_embeddings(queries_embs, documents_embs, K=len(documents))
vector_score_boosts = []
for i, query in tqdm(enumerate(queries)):
    score_boost = {document_ids[j]: s for j, s in zip(selected_documents_ids[i], search_scores[i], strict=False)}
    vector_score_boosts.append(score_boost)

100%|██████████| 2/2 [00:00<00:00, 1253.34it/s]
2it [00:00, 16256.99it/s]

In [28]:
# Step 1: If ranks match -> select this document:
selected_docs_step_1, candidates, snippets, doc_texts = [], [], [], []
for i, q in tqdm(enumerate(queries)):
    rank_lexical = get_ranking(lexical_score_boosts[i])
    rank_vector = get_ranking(vector_score_boosts[i])
    if rank_lexical[0] == rank_vector[0]:
        selected_docs_step_1.append(rank_lexical[0])
        candidates.append(None)
        snippets.append(None)
        doc_texts.append(None)
    else:  # if not prepare your ass for reranking
        selected_docs_step_1.append(None)
        candidates_query = list(set(rank_lexical[:2]) | set(rank_vector[:2]))
        candidates.append(candidates_query)
        snippets.append(
            [
                documents[document_ids.index(doc_id)].document_title
                + " "
                + get_lexical_snippet(corpus[document_ids.index(doc_id)], sanitize_tantivy_query(q.question_text))
                for doc_id in candidates_query
            ]
        )
        doc_texts.append([documents[document_ids.index(doc_id)].pages_text[:MAX_LEN] for doc_id in candidates_query])

# Step 2: If ranks unmatch we apply reranker in the game:
for i, d in tqdm(enumerate(selected_docs_step_1)):
    if d is None:  # document is not selected on step 1:
        query = queries[i].question_text
        local_candidates = candidates[i]
        local_snippets = snippets[i]
        local_doc_headers = doc_texts[i]

        texts_to_rank = [
            f"Заголовок: {h}\n\n Контент: {c}" for h, c in zip(local_doc_headers, local_snippets, strict=False)
        ]
        results = reranker.rerank(query, texts_to_rank)
        selected_docs_step_1[i] = local_candidates[results[0]["index"]]

input_df["Doc_ID_pred"] = selected_docs_step_1
if TRAIN:
    print((input_df["Doc_ID_pred"] == input_df["Doc_ID"]).mean())

2it [00:00, 29852.70it/s]
2it [00:00, 38304.15it/s]

# Pages search:

In [29]:
def chunk_markdown(pages_dict, max_chars=500, overlap_chars=50):
    chunks = []
    active_context = "Загальна інформація"

    def break_down_large_block(text, max_length):
        """Breaks down a massive block into lines or sentences if it exceeds max_length."""
        if len(text) <= max_length:
            return [text]

        pieces = []
        for line in text.split("\n"):
            if len(line) <= max_length:
                pieces.append(line)
            else:
                # Split by sentence boundaries (e.g., period, exclamation, or question mark followed by space)
                sentences = re.split(r"(?<=[.!?])\s+", line)
                pieces.extend(sentences)

        return [p.strip() for p in pieces if p.strip()]

    # Iterate through each page strictly
    for page_num, page_text in pages_dict.items():
        # 2. Reset state for each new page to guarantee chunks don't cross pages
        current_chunk_text = ""
        current_contexts = []
        blocks = re.split(r"\n{2,}", page_text.strip())

        def save_chunk(is_page_end=False):
            nonlocal current_chunk_text, current_contexts, active_context

            clean_text = current_chunk_text.strip()
            if not clean_text:
                return

            # 3. Return context as list of strings (deduplicated, order preserved)
            unique_contexts = list(dict.fromkeys(current_contexts))
            context_list = unique_contexts if unique_contexts else [active_context]

            # Save text and context as separate fields
            chunks.append(
                {
                    "page_number": page_num,  # Single page reference
                    "context": context_list,
                    "text": clean_text,
                    "length": len(clean_text),
                }
            )

            # 1. Handle minimal overlap
            if not is_page_end and overlap_chars > 0 and len(clean_text) > overlap_chars:
                # Extract the end of the text for overlap
                overlap_text = clean_text[-overlap_chars:]
                # Try to snap to the first space to avoid cutting words in half
                space_idx = overlap_text.find(" ")
                if space_idx != -1 and space_idx < len(overlap_text) - 1:
                    overlap_text = overlap_text[space_idx + 1 :]

                current_chunk_text = overlap_text + " "
                # Keep the most recent context for the overlap portion
                current_contexts = [context_list[-1]] if context_list else [active_context]
            else:
                # Fully reset if it's the end of a page or no overlap is configured
                current_chunk_text = ""
                current_contexts = []

        for block in blocks:
            block = block.strip()
            if not block:
                continue

            new_context = None
            first_line = block.split("\n")[0].strip()

            # --- HEURISTIC 1: Markdown Headers (# Header) ---
            md_match = re.match(r"^#+\s+(.*)", first_line)
            if md_match:
                raw_header = md_match.group(1)

                # If the parser squashed the header and text together
                bold_match = re.search(r"[_*]{2}(.*?)[_*]{2}", raw_header)
                if bold_match:
                    new_context = bold_match.group(1).strip(" .:")
                else:
                    # Fallback: take the header text up to the first period, or the whole thing if it's short
                    new_context = (
                        raw_header.split(".")[0].strip(" .:") if len(raw_header) > 60 else raw_header.strip(" .:")
                    )

            # --- HEURISTIC 2: Bold/Italic at the start of the line (without #) ---
            elif re.match(r"^[_*]+([^_*]+)[_*]+", first_line):
                new_context = re.match(r"^[_*]+([^_*]+)[_*]+", first_line).group(1).strip(" .:")

            # --- HEURISTIC 3: Short starting phrase (Run-in headers) ---
            # Finds the first phrase ending in a period or colon at the start of the block
            match = re.match(r"^([^.:]+[.:])", block)
            if match:
                potential_context = match.group(1).strip()

                # Must start with a capital letter
                if potential_context and potential_context[0].isupper():
                    # Count words by splitting on whitespace
                    word_count = len(potential_context.split())

                    # Rule 1: Ends with '.' and max 3 words
                    if potential_context.endswith(".") and word_count <= 3:
                        new_context = potential_context.rstrip(".").strip()

                    # Rule 2: Ends with ':' and max 8 words
                    elif potential_context.endswith(":") and word_count <= 8:
                        new_context = potential_context.rstrip(":").strip()

            # Update the running context if we found a new one
            if new_context:
                active_context = new_context

            # Break down the block if it's too large, otherwise it returns the block as a single item
            sub_blocks = break_down_large_block(block, max_chars)

            for sub_block in sub_blocks:
                # Check if adding this sub_block exceeds the limit
                if len(current_chunk_text) + len(sub_block) > max_chars and current_chunk_text.strip():
                    save_chunk(is_page_end=False)

                # Ensure correct spacing between concatenated pieces
                if current_chunk_text and not current_chunk_text.endswith(("\n", " ")):
                    current_chunk_text += " "

                # Add the sub_block to the current chunk
                current_chunk_text += sub_block
                current_contexts.append(active_context)

            # Add a double newline at the end of the original block to preserve visual paragraph spacing
            if current_chunk_text:
                current_chunk_text = current_chunk_text.rstrip() + "\n\n"

        # Force a save at the end of the page to ensure no text bleeds into the next page
        if current_chunk_text.strip():
            save_chunk(is_page_end=True)

    return chunks

In [30]:
# all_parsed_chunked = {}
# for doc_name, pages in tqdm(all_parsed.items()):
#     page_chunks = [{
#         'page_number': chunk["page_number"],
#         'doc_id': doc_name,
#         'full_text': chunk["full_text"],
#         'full_text_clean': clean_for_search(chunk["full_text"]),
#         "full_text_processed": sanitize_tantivy_query(chunk["full_text"]),
#     } for chunk in pages]
#     all_parsed_chunked[doc_name] = page_chunks


MAX_SIZE = 500

all_parsed_chunked = {}
for doc_name, pages in tqdm(all_parsed.items()):
    pages = {e["page_number"]: e["full_text"] for e in all_parsed[doc_name]}
    chunks = chunk_markdown(pages, max_chars=MAX_SIZE)
    page_chunks = [
        {
            "page_number": chunk["page_number"],  # <--- Not the proper way, but let it be.....
            "doc_id": doc_name,
            "context": chunk["context"],
            "context_processed": sanitize_tantivy_query(" ".join(chunk["context"])),
            "full_text": chunk["text"],
            "full_text_clean": clean_for_search(
                " ".join([c for c in chunk["context"] if c not in chunk["text"]]) + " " + chunk["text"]
            ),
            "full_text_processed": sanitize_tantivy_query(
                " ".join([c for c in chunk["context"] if c not in chunk["text"]]) + " " + chunk["text"]
            ),
            "full_text_page": pages[chunk["page_number"]],
        }
        for chunk in chunks
    ]
    all_parsed_chunked[doc_name] = page_chunks

100%|██████████| 2/2 [00:03<00:00,  1.51s/it]

In [31]:
pages_embeddings = {}
for doc_name, chunks_list in tqdm(all_parsed_chunked.items()):
    pages_embeddings[doc_name] = embed_with_sliding_window(
        [c["full_text_clean"] for c in chunks_list], show_progress_bar=False, window_size=5
    )

# pages_embeddings = {}
# for doc_name, chunks_list in tqdm(all_parsed_chunked.items()):
#     pages_embeddings[doc_name] = embed_any([c["full_text_clean"] for c in chunks_list], show_progress_bar=False)

100%|██████████| 2/2 [01:38<00:00, 49.21s/it]

In [32]:
for obj_name in ["model", "tokenizer", "embed_any", "embed_with_sliding_window", "model_ctx", "reranker"]:
    if obj_name in globals():
        try:
            del globals()[obj_name]
        except:
            pass

import gc

import torch

gc.collect()
gc.collect()  # second pass catches reference cycles
torch.cuda.empty_cache()
torch.cuda.synchronize()

print(f"Memory cleanup done. GPU memory allocated: {torch.cuda.memory_allocated() / 1024**2:.0f} MB")

Memory cleanup done. GPU memory allocated: 1147 MB

In [33]:
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer


class RerankerInference:
    def __init__(self, model_path="./BAAI_chunk_reranker/best", device=None):
        """
        Loads the trained model and tokenizer into memory.
        """
        self.device = device if device else ("cuda" if torch.cuda.is_available() else "cpu")
        print(f"Loading model from {model_path} onto {self.device}...")

        self.tokenizer = AutoTokenizer.from_pretrained(model_path)
        self.model = AutoModelForSequenceClassification.from_pretrained(model_path).to(self.device)
        self.model.eval()

    @torch.no_grad()
    def get_sorted_indices(self, query: str, texts: list[str], max_length: int = 1500) -> list[int]:
        """
        Takes a query and a list of texts, returns the indices of the texts
        sorted from most relevant to least relevant.
        """
        if not texts:
            return []

        # 1. Format queries exactly as done during training
        formatted_queries = [f"Питання: {query}"] * len(texts)

        # 2. Tokenize
        inputs = self.tokenizer(
            formatted_queries, texts, padding=True, truncation=True, max_length=max_length, return_tensors="pt"
        ).to(self.device)

        # 3. Forward pass (using mixed precision for speed)
        with torch.amp.autocast(device_type="cuda" if "cuda" in self.device else "cpu", dtype=torch.bfloat16):
            logits = self.model(**inputs).logits.squeeze(-1)

        # Handle edge case where there's only 1 text (squeeze might remove the batch dimension entirely)
        if logits.dim() == 0:
            logits = logits.unsqueeze(0)

        # 4. Sort logits in descending order (highest score first) and get indices
        sorted_indices = torch.argsort(logits, descending=True).tolist()

        return sorted_indices


# =========================
# USAGE EXAMPLE
# =========================
# Initialize the class once
reranker = RerankerInference(
    model_path="/kaggle/input/models/trokhymovych/rerankrer/transformers/default/1/BAAI_chunk_reranker/best"
)

# Example data
test_query = "Який розмір мінімальної пенсії в Україні?"
test_chunks = [
    "Погода в Києві сьогодні сонячна, температура повітря становить 20 градусів.",  # Index 0 (Irrelevant)
    "Згідно з новим законом, мінімальна пенсія в Україні становить 2361 грн.",  # Index 1 (Most Relevant)
    "Для оформлення пенсії необхідно звернутися до Пенсійного фонду з паспортом.",  # Index 2 (Somewhat Relevant)
]

# Run inference
sorted_idx = reranker.get_sorted_indices(test_query, test_chunks)

print(f"\nQuery: {test_query}")
print(f"Sorted Indices: {sorted_idx}")

print("\nTexts in order of relevance:")
for rank, idx in enumerate(sorted_idx, 1):
    print(f"{rank}. [Index {idx}] {test_chunks[idx]}")

Loading model from /kaggle/input/models/trokhymovych/rerankrer/transformers/default/1/BAAI_chunk_reranker/best onto cuda...

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

Query: Який розмір мінімальної пенсії в Україні?
Sorted Indices: [1, 2, 0]

Texts in order of relevance:
1. [Index 1] Згідно з новим законом, мінімальна пенсія в Україні становить 2361 грн.
2. [Index 2] Для оформлення пенсії необхідно звернутися до Пенсійного фонду з паспортом.
3. [Index 0] Погода в Києві сьогодні сонячна, температура повітря становить 20 градусів.

In [34]:
# Pages search (within found documents):
from collections import defaultdict
import gc

import torch
from tqdm.auto import tqdm


def reciprocal_rank_fusion(rankings, k=60):
    """
    Args:
        rankings: A list of lists, where each inner list is a
                  ranking of document IDs (strings).
        k: A smoothing constant (60 is the standard recommendation).
    """
    rrf_score = defaultdict(float)
    for ranking in rankings:
        for rank, doc_id in enumerate(ranking):
            # rank starts at 0, so we use (rank + 1)
            # Formula: 1 / (k + rank)
            rrf_score[doc_id] += 1.0 / (k + rank + 1)

    # Sort documents by their new RRF score descending
    sorted_docs = sorted(rrf_score.items(), key=lambda x: x[1], reverse=True)
    return [doc[0] for doc in sorted_docs]


selected_pages, selected_pages_data_full, recall_3, recall_5 = [], [], [], []
for i in tqdm(range(len(input_df))):
    doc = input_df.iloc[i].Doc_ID_pred
    doc_page_embeddings = np.array(pages_embeddings[doc])
    query = queries[i]

    if doc_page_embeddings is None:  # Emergency handling, is not happening on train data
        selected_pages.append(1)
        selected_pages_data_full.append([])
        print("Mistake looking for page")
        continue

    #### Vector Boosts: #### TODO: SEARCH FOR EACH OPTION SEPARATLY AND MIX
    selected_page_ids, selected_page_scores = search_embeddings(
        [query.question_text_all_options_embeddings],
        doc_page_embeddings,
        K=len(doc_page_embeddings),  # I need scores for all to boost by BM25 score.
    )
    vector_score_boosts = {j: s for j, s in zip(selected_page_ids[0], selected_page_scores[0], strict=False)}

    #### LEXICAL BOOSTS ####
    lexical_query = sanitize_tantivy_query(query.question_text + " ".join(query.question_options))
    pages_to_score = all_parsed_chunked[doc]
    corpus = [page["full_text_processed"] for page in pages_to_score]
    tokenized_corpus = [doc.lower().split(" ") for doc in corpus]
    bm25 = BM25Okapi(tokenized_corpus)
    pages_ids = np.arange(0, len(pages_to_score))
    lexical_score_boosts = calculating_documets_boosts(lexical_query, bm25, pages_ids)

    #### FINAL RANKING ####
    lexical_ranks = get_ranking(lexical_score_boosts)
    vector_ranks = get_ranking(vector_score_boosts)
    final_ranking = reciprocal_rank_fusion([vector_ranks, lexical_ranks])

    # Final prediction without reranker:
    top_items = final_ranking[:100]
    # print(top_items)
    selected_page_idx = top_items[0]
    selected_page = pages_to_score[selected_page_idx]["page_number"]
    selected_pages.append(selected_page)

    selected_pages_data, pages_used = [], []
    for k in top_items:
        if pages_to_score[k]["page_number"] not in pages_used:
            selected_pages_data.append(pages_to_score[k])
            pages_used.append(pages_to_score[k]["page_number"])
    # selected_pages_data_full.append(selected_pages_data)
    # reranking:
    sorted_idx = reranker.get_sorted_indices(
        query.question_text
        + " Можливі відповіді: "
        + ", ".join(input_df.iloc[i][["A", "B", "C", "D", "E", "F"]].values),
        [p["full_text"] for p in selected_pages_data][:16],
    )
    selected_pages_data_resorted = [selected_pages_data[i] for i in sorted_idx]
    selected_pages_data_full.append(selected_pages_data_resorted)

    if TRAIN:
        # top_items = final_ranking[:16]
        # used_pages = []
        # for item in top_items:
        #     if not pages_to_score[item]["page_number"] in used_pages:
        #         used_pages.append(pages_to_score[item]["page_number"])
        used_pages = [p["page_number"] for p in selected_pages_data_resorted]
        recall_3.append(input_df.iloc[i].Page_Num in used_pages[:3])
        recall_5.append(input_df.iloc[i].Page_Num in used_pages[:8])

input_df["Page_Num_pred"] = selected_pages
input_df["retrieved_chunks"] = selected_pages_data_full

# Metrics for debuging in train phase:
if TRAIN:
    print("Document search accuracy: ", (input_df["Doc_ID_pred"] == input_df["Doc_ID"]).mean())
    page_is_correct = (input_df["Doc_ID_pred"] == input_df["Doc_ID"]) & (
        input_df["Page_Num_pred"] == input_df["Page_Num"]
    )
    print("Exact page found: ", page_is_correct.mean())

    def page_score_np(page_pred, page_true, n_pages, d):
        """Compute the page score using numpy."""
        score = (1 - np.abs(page_pred - page_true) / n_pages) * d
        return score

    page_scores = []
    for _, row in input_df.iterrows():
        doc_is_correct = row["Doc_ID_pred"] == row["Doc_ID"]
        page_scores.append(page_score_np(row["Page_Num_pred"], row["Page_Num"], row["N_Pages"], doc_is_correct))
    print("Page score: ", np.mean(page_scores))
    print("Recall 3: ", np.mean(recall_3))
    print("Recall 4: ", np.mean(recall_5))

  0%|          | 0/2 [00:00<?, ?it/s]

# Inferencing LLM:

In [37]:
for obj_name in [
    "hybrid_preds",
    "hybrid_with_fallback",
    "rescue_log",
    "kw_rescue_log",
    "revert_log",
    "selected_documents_names",
    "corpus",
    "tokenized_corpus",
    "bm25",
    "all_parsed",
    "model",
    "doc_fingerprints",
    "doc_full_texts",
    "all_parsed",
    "all_parsed_chunked",
    "tantivy_idx",
    "tantivy_docs",
    "tantivy_top1_per_query",
    "pages_embeddings",
    "queries_embs",
    "documents_embs",
    "emb_sim_matrix",
    "emb_rankings",
    "emb_scores_per_query",
    "queries",
    "results_optim",
    "selected_documents_ids",
    "search_scores",
    "model",
    "tokenizer",
    "doc_map",
    "document_ids",
    "lexical_score_boosts",
    "ranked_predictions",
    "best_result",
    "data_files",
    "file_path_to_id",
    "morph",
    "embed_any",  # closure holds a reference to the SentenceTransformer on GPU
    "embed_with_sliding_window",
    "all_parsed_chunked",
    "pages_embeddings",
    "selected_pages",
    "llm",
    "selected_pages_data",
    "model_ctx",
    "reranker",
    "results",
    "embed_with_sliding_window",
    "reranker",
    "get_lexical_snippet",
    "calculating_documets_boosts",
    "get_ranking",
    "documents_embeddings",
    "config",
    "queries_embeddings",
    "documents_embeddings",
    "get_lexical_snippet",
    "calculating_documets_boosts",
    "get_ranking",
    "vector_score_boosts",
    "lexical_score_boosts",
    "reciprocal_rank_fusion",
]:
    if obj_name in globals():
        try:
            del globals()[obj_name]
        except:
            pass

import gc

import torch

gc.collect()
gc.collect()  # second pass catches reference cycles
torch.cuda.empty_cache()
torch.cuda.synchronize()

print(f"Memory cleanup done. GPU memory allocated: {torch.cuda.memory_allocated() / 1024**2:.0f} MB")

Memory cleanup done. GPU memory allocated: 1148 MB

In [38]:
2**13

8192

In [39]:
MODEL_PATH = "/kaggle/input/models/trokhymovych/mamay-unlp/gguf/500-iterations/3/mamay_finetuned_v3_Q4_K_M.gguf"
MODEL_PATH

'/kaggle/input/models/trokhymovych/mamay-unlp/gguf/500-iterations/3/mamay_finetuned_v3_Q4_K_M.gguf'

In [40]:
llm = Llama(
    model_path=MODEL_PATH,
    n_ctx=8192,  # 14 = 16k ~ 14 Gi VRAM
    n_gpu_layers=-1,
    n_batch=512,
    n_threads=4,
    verbose=False,
)

llama_context: n_ctx_per_seq (8192) < n_ctx_train (131072) -- the full capacity of the model will not be utilized
llama_kv_cache_unified_iswa: using full-size SWA cache (ref: https://github.com/ggml-org/llama.cpp/pull/13194#issuecomment-2868343055)

In [41]:
import time

CHARS_PER_TOKEN = 3

CONTEXT_CHAR_LIMIT = 6000
LLM_CTX = 8192
LLM_TEMPERATURE = 0.0
LLM_MAX_TOKENS = 10
LABELS = ["A", "B", "C", "D", "E", "F"]


MAX_PROMPT_TOKENS = LLM_CTX - LLM_MAX_TOKENS - 64


def build_user_prompt(row, chunks) -> str:
    options = "\n".join(f"{lab}: {row[lab]}" for lab in LABELS)
    fixed_text = (
        f"Запитання: {row['Question']}\n"
        f"Варіанти:\n{options}\n"
        f"Інструкція:\n"
        f"- Дай відповідь на Запитання використовуючи Контекст.\n"
        f"- Поверни літеру правильної відповіді ({' '.join(LABELS)}) "
        f"та номер сторінки, на якій знайдено інформацію, "
        f"через пробіл (наприклад: A 1).\n"
        f"- Добре подумай, спочатку відкинь очевидно нерелевантні відповіді."
    )

    ctx_header = (
        "Контекст (уривки з PDF-файлів - кожен уривок розділений "
        "з допомогою символів ``` та містить номер сторінки "
        "виділений за допомогою []):\n"
    )

    char_budget = MAX_PROMPT_TOKENS * CHARS_PER_TOKEN - len("Контекст:\n") - len(ctx_header) - len(fixed_text) - 30

    ctx_parts = []
    total_len = 0
    for chunk in chunks:
        pnum = chunk["page_number"]
        text = chunk["full_text_page"]
        part = f"Сторінка: [{pnum}]\n{text}"
        sep_len = len("\n```\n") if ctx_parts else 0
        if total_len + sep_len + len(part) > char_budget:
            break
        ctx_parts.append(part)
        total_len += sep_len + len(part)

    ctx_body = "\n```" + "```\n\n```".join(ctx_parts) + "\n```"

    usr_prompt = f"{ctx_header}{ctx_body}\n\n\n{fixed_text}"
    # print(usr_prompt)
    return usr_prompt


def parse_answer(text: str):
    """Parse letter and page number from model output like 'A 1' or 'B 23'."""
    text = text.strip()
    parts = text.split()

    letter = None
    page = None
    for part in parts:
        ch = part.upper()
        if ch in LABELS and letter is None:
            letter = ch
        elif part.isdigit() and page is None:
            page = int(part)

    return letter or "F", page


def predict_answer(row, chunks):
    user_prompt = build_user_prompt(row, chunks)
    # print(user_prompt)
    try:
        response = llm.create_chat_completion(
            messages=[{"role": "user", "content": user_prompt}],
            temperature=LLM_TEMPERATURE,
            max_tokens=LLM_MAX_TOKENS,
        )
        text = response["choices"][0]["message"]["content"].strip()
        # print(text)
        if text:
            return parse_answer(text)
        return "F", None
    except Exception as e:
        print(f"LLM error on Q{row.get('Question_ID', '?')}: {e}")
        return "F", None

In [42]:
predicted_answers = []
predicted_llm_pages = []

t0 = time.time()

for qi in tqdm(range(len(input_df)), desc="LLM inference"):
    row = input_df.iloc[qi]
    chunks = row["retrieved_chunks"]
    chunks = chunks[:3]
    ans, page = predict_answer(row, chunks)
    predicted_answers.append(ans)
    predicted_llm_pages.append(page)

    # print(ans, page)
    # break

final_page_nums = [
    llm_p if llm_p is not None else ret_p
    for llm_p, ret_p in zip(predicted_llm_pages, input_df["Page_Num_pred"], strict=False)
]

llm_page_count = sum(1 for p in predicted_llm_pages if p is not None)
elapsed = time.time() - t0
print(f"Inference done in {elapsed / 60:.1f} min ({elapsed / len(input_df):.2f}s per question)")
print(f"LLM returned page numbers for {llm_page_count}/{len(input_df)} questions")

LLM inference:   0%|          | 0/2 [00:00<?, ?it/s]

Inference done in 0.3 min (8.25s per question)
LLM returned page numbers for 2/2 questions

In [43]:
input_df["pred_answer"] = predicted_answers
input_df["Page_Num_pred"] = final_page_nums

# Building Submission File:

In [44]:
if TRAIN:
    print((input_df["Correct_Answer"] == input_df["pred_answer"]).mean())

In [45]:
# input_df["pred_answer"] = "G" # Incorrect in purpose (no need to burn GPU for now)


columns_to_save = ["Question_ID", "pred_answer", "Doc_ID_pred", "Page_Num_pred"]
columns_names = ["Question_ID", "Correct_Answer", "Doc_ID", "Page_Num"]

pred_df = input_df[columns_to_save].copy()
pred_df.columns = columns_names

# Safety: ensure no NaN values in submission
assert pred_df["Correct_Answer"].notna().all(), "Some answers are NaN!"
assert pred_df["Doc_ID"].notna().all(), "Some Doc_IDs are NaN!"
assert pred_df["Page_Num"].notna().all(), "Some Page_Nums are NaN!"

pred_df.to_csv("submission.csv", index=False)
print(f"Submission file saved successfully! Shape: {pred_df.shape}")
pred_df.head()

Submission file saved successfully! Shape: (2, 4)

   Question_ID Correct_Answer                                        Doc_ID  Page_Num
0            0              B  759dfc8486c0f02391d7cfc1fed753b0608fc601.pdf        43
1            4              D  aba537442395c1a4ca13d05e378a49a47865cc46.pdf        14

In [46]:
def compute_competition_score_final(solution, submission, n_pages_column="n_pages"):
    """Official competition scoring: answer 50% + doc 25% + page proximity 25%."""
    answer_metric = (solution["Correct_Answer"].values == submission["Correct_Answer"].values).mean()

    doc_mask = solution["Doc_ID"].values == submission["Doc_ID"].values
    doc_metric = doc_mask.mean()

    page_metric = np.mean(
        (
            1
            - np.abs(solution["Page_Num"].values - submission["Page_Num"].values).astype(float)
            / solution[n_pages_column].values.astype(float)
        )
        * doc_mask.astype(float)
    )

    final_score = answer_metric * 0.5 + doc_metric * 0.25 + page_metric * 0.25

    print(f"  Answer accuracy:  {answer_metric:.4f}  (×0.50 = {answer_metric * 0.5:.4f})")
    print(f"  Doc match:        {doc_metric:.4f}  (×0.25 = {doc_metric * 0.25:.4f})")
    print(f"  Page proximity:   {page_metric:.4f}  (×0.25 = {page_metric * 0.25:.4f})")
    print(f"  Final score:      {final_score:.4f}")

    return float(answer_metric), float(doc_metric), float(page_metric), float(final_score)


if TRAIN:
    solution = input_df[["Correct_Answer", "Doc_ID", "Page_Num", N_PAGES_COLUMN]].copy()
    solution.columns = ["Correct_Answer", "Doc_ID", "Page_Num", "n_pages"]

    submission = pred_df.copy()

    print("=== Final Competition Score (with LLM answers) ===")
    answer_metric, doc_metric, page_metric, final_score = compute_competition_score_final(
        solution, submission, n_pages_column="n_pages"
    )